/* Church template catalog.
 *
 * Lobby screens, sanctuary side panels and foyer posters for a local
 * congregation: service times, the current sermon series, giving and prayer
 * QRs, kids check-in, small groups, missions reporting and the seasonal
 * services that fill the room twice a year.
 *
 * Sample church is "Grace Chapel" on Millbrook Road — the operator swaps the
 * name, times and rooms; everything else is ready to hang on a wall.
 */

export default {
  category: 'church',
  name: 'Church',
  description: 'Service times, sermon series, giving and prayer QRs, groups and seasonal service announcements for congregations.',
  icon: '⛪',
  templates: [
    {
      key: 'welcome-guests',
      name: 'Welcome Home',
      description: 'Warm lobby welcome with a connect-card QR.',
      tags: ['welcome', 'lobby'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        eyebrow: 'GRACE CHAPEL',
        title: 'Welcome Home',
        titleSize: 0.11,
        body: 'However you found us this morning, there is a seat saved for you. Coffee is on in the lobby.',
        cta: 'Say hello at the Welcome Desk',
        qr: 'https://example.com/connect',
        qrLabel: 'Connect card',
      },
    },
    {
      key: 'service-times',
      name: 'Sunday Service Times',
      description: 'Both morning gathering times with nursery note.',
      tags: ['services', 'times'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        eyebrow: 'SUNDAY GATHERINGS',
        title: '9:00 & 11:00 AM',
        titleSize: 0.14,
        body: 'Nursery and kids ministry at both services. Doors open thirty minutes early.',
        footer: 'Grace Chapel  |  412 Millbrook Road',
      },
    },
    {
      key: 'weekly-schedule',
      name: 'This Week at Church',
      description: 'Eight-row board of every gathering this week.',
      tags: ['schedule', 'weekly'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        title: 'This Week at Grace',
        subtitle: 'August 17 - 23',
        colTime: 'WHEN',
        colName: 'GATHERING',
        colMeta: 'WHERE',
        rows: [
          ['Sun 9:00 AM', 'Morning Worship', 'Sanctuary'],
          ['Sun 11:00 AM', 'Morning Worship', 'Sanctuary'],
          ['Mon 6:30 PM', 'Men\'s Bible Study', 'Room 204'],
          ['Tue 9:30 AM', 'Women of the Word', 'Fireside Room'],
          ['Wed 6:00 PM', 'Youth Group', 'The Loft'],
          ['Wed 7:15 PM', 'Choir Rehearsal', 'Choir Room'],
          ['Thu 6:30 PM', 'Celebrate Recovery', 'Fellowship Hall'],
          ['Sat 8:00 AM', 'Prayer Breakfast', 'Fellowship Hall'],
        ],
      },
    },
    {
      key: 'sermon-series',
      name: 'Current Sermon Series',
      description: 'Series art with week marker and notes QR.',
      tags: ['sermon', 'series'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'violet',
        eyebrow: 'CURRENT SERIES',
        title: 'Rooted',
        titleSize: 0.15,
        body: 'A six-week walk through Colossians. This week: Alive Together in Christ.',
        cta: 'Follow along',
        scrim: 66,
        qr: 'https://example.com/sermon-notes',
        qrLabel: 'Sermon notes',
      },
    },
    {
      key: 'verse-of-the-day',
      name: 'Verse of the Day',
      description: 'Portrait scripture card for the foyer.',
      tags: ['scripture', 'daily'],
      recipe: 'quoteCard',
      orientation: 'portrait',
      spec: {
        palette: 'paper',
        display: 'playfair',
        quote: 'Be strong and courageous. The Lord your God goes with you.',
        quoteSize: 0.05,
        author: 'Deuteronomy 31:6',
        footer: 'VERSE OF THE DAY',
      },
    },
    {
      key: 'giving-qr',
      name: 'Give Online',
      description: 'Portrait giving poster with scan-to-give QR.',
      tags: ['giving', 'tithe'],
      recipe: 'infoCard',
      orientation: 'portrait',
      spec: {
        palette: 'forest',
        title: 'Give Online',
        fields: [
          { label: 'Text to give', value: 'GIVE to 55555', mono: true },
          { label: 'Online', value: 'gracechapel.org/give' },
          { label: 'In person', value: 'Offering boxes at both exits' },
        ],
        body: 'Every gift supports ministry here and around the world.',
        qr: 'https://example.com/give',
        qrLabel: 'Scan to give',
      },
    },
    {
      key: 'prayer-request',
      name: 'Prayer Request QR',
      description: 'Invitation to send a request to the prayer team.',
      tags: ['prayer', 'care'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'teal',
        eyebrow: 'WE WOULD LOVE TO PRAY',
        title: 'Need Prayer?',
        titleSize: 0.13,
        body: 'Send a request to our prayer team. Every one is read and prayed over.',
        qr: 'https://example.com/prayer',
        qrLabel: 'Send a request',
      },
    },
    {
      key: 'upcoming-events',
      name: 'Upcoming Events',
      description: 'Six dated events with location details.',
      tags: ['events', 'calendar'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'amber',
        title: 'Upcoming at Grace',
        subtitle: 'Fall 2026',
        colTime: 'DATE',
        colName: 'EVENT',
        colMeta: 'DETAILS',
        rows: [
          ['Aug 23', 'All-Church Picnic', 'Millbrook Park, noon'],
          ['Aug 30', 'New Member Class', 'Room 110, 9 AM'],
          ['Sep 6', 'Baptism Sunday', 'Both services'],
          ['Sep 20', 'Fall Serve Day', 'Meet in the lobby, 8 AM'],
          ['Sep 27', 'Youth Fall Retreat', 'Camp Winona'],
          ['Oct 4', 'Harvest Festival', 'Back lot, 5 PM'],
        ],
      },
    },
    {
      key: 'youth-group',
      name: 'Youth Group Night',
      description: 'Midweek student ministry promo, photo right.',
      tags: ['youth', 'students'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'crimson',
        eyebrow: 'GRADES 6-12',
        title: 'Wednesday Nights',
        body: 'Games at six, worship and small groups at seven. Bring a friend and a snack.',
        cta: 'The Loft, upper level',
        flip: true,
      },
    },
    {
      key: 'volunteer-signup',
      name: 'Serve on a Team',
      description: 'Four steps from interest to first Sunday serving.',
      tags: ['volunteer', 'serve'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'steel',
        title: 'Serve on a Team',
        steps: [
          ['Pick a team', 'Kids, worship, hospitality, parking or media.'],
          ['Fill out the card', 'Two minutes at the Welcome Desk.'],
          ['Meet your leader', 'A team coach calls you within a week.'],
          ['Shadow a Sunday', 'Try it out before you commit to anything.'],
        ],
        footer: 'EVERY SEAT FILLED STARTS WITH ONE YES',
      },
    },
    {
      key: 'baptism-sunday',
      name: 'Baptism Sunday',
      description: 'Full-bleed baptism announcement with sign-up QR.',
      tags: ['baptism', 'announcement'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        eyebrow: 'SEPTEMBER 6',
        title: 'Baptism Sunday',
        body: 'Ready for the next step? Sign up by August 30 and we will walk you through it.',
        cta: 'Sign up today',
        anchor: 'bottom',
        scrim: 68,
        qr: 'https://example.com/baptism',
        qrLabel: 'Sign up',
      },
    },
    {
      key: 'worship-set',
      name: 'Worship Song List',
      description: 'This morning\'s set list with keys, two columns.',
      tags: ['worship', 'music'],
      recipe: 'menuBoard',
      orientation: 'landscape',
      spec: {
        palette: 'charcoal',
        title: 'This Morning\'s Worship',
        subtitle: 'SUNDAY, AUGUST 17',
        columns: 2,
        sections: [
          {
            name: 'OPENING',
            items: [
              ['Great Are You Lord', 'Key of A'],
              ['King of Kings', 'Key of D'],
              ['Goodness of God', 'Key of A flat'],
            ],
          },
          {
            name: 'RESPONSE',
            items: [
              ['Build My Life', 'Key of G'],
              ['The Blessing', 'Key of B'],
              ['Doxology', 'Key of C'],
            ],
          },
        ],
        footer: 'LYRICS ON SCREEN  |  HYMNALS IN THE PEW RACKS',
      },
    },
    {
      key: 'small-groups',
      name: 'Small Groups Directory',
      description: 'Ten groups with night, time and room.',
      tags: ['groups', 'directory'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'sand',
        title: 'Small Groups This Fall',
        entries: [
          ['Young Adults', 'Mon 7 PM, Room 204'],
          ['Men\'s Study', 'Tue 6:30 AM, Fireside'],
          ['Women of the Word', 'Tue 9:30 AM, Room 110'],
          ['Marriage Group', 'Tue 7 PM, host homes'],
          ['Empty Nesters', 'Wed 6 PM, Room 208'],
          ['New Parents', 'Wed 6 PM, Nursery Wing'],
          ['Grief Share', 'Thu 6:30 PM, Room 112'],
          ['Grupo en Espanol', 'Thu 7 PM, Fellowship Hall'],
          ['Seniors Fellowship', 'Fri 10 AM, Fireside'],
          ['Saturday Prayer', 'Sat 8 AM, Sanctuary'],
        ],
        footer: 'ROOM NUMBERS POSTED IN THE HALLWAY',
      },
    },
    {
      key: 'group-signup',
      name: 'Group Sign-Ups Open',
      description: 'Push to join a fall small group, with QR.',
      tags: ['groups', 'signup'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'espresso',
        eyebrow: 'FALL SEMESTER',
        title: 'Find Your Group',
        titleSize: 0.13,
        body: 'Groups start the week of September 8. Sign up before they fill.',
        qr: 'https://example.com/groups',
        qrLabel: 'Browse groups',
      },
    },
    {
      key: 'missions-update',
      name: 'Missions Update',
      description: 'Four partner stats from the summer report.',
      tags: ['missions', 'stats'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'forest',
        title: 'Missions Update',
        subtitle: 'SUMMER 2026 PARTNER REPORT',
        tiles: [
          { label: 'Countries', value: '11', sub: 'Active partners' },
          { label: 'Wells drilled', value: '34', sub: 'Clean water for 8,200' },
          { label: 'Meals packed', value: '62,000', sub: 'One volunteer weekend' },
          { label: 'Sent out', value: '19', sub: 'Long-term missionaries', accent: '#4ade80' },
        ],
        footer: 'THANK YOU FOR SENDING THEM',
      },
    },
    {
      key: 'kids-checkin',
      name: 'Kids Check-In Steps',
      description: 'Four-step kiosk check-in for parents.',
      tags: ['kids', 'checkin'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'clinical',
        title: 'Kids Check-In',
        steps: [
          ['Stop at a kiosk', 'Type your phone number to find your family.'],
          ['Print your tags', 'One for your child, one for you.'],
          ['Walk to the room', 'Age groups are posted above each door.'],
          ['Pick up after', 'Matching tag required at the door.'],
        ],
        footer: 'NURSERY THROUGH 5TH GRADE  |  LOWER LEVEL',
      },
    },
    {
      key: 'first-time-guest',
      name: 'First Time Here',
      description: 'Guest card with lobby, coffee and kids info.',
      tags: ['guest', 'welcome'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'mono',
        title: 'First Time Here?',
        fields: [
          { label: 'Welcome Desk', value: 'Main lobby, look for the blue shirts' },
          { label: 'Coffee', value: 'Free in the cafe until 11:30' },
          { label: 'Kids', value: 'Check in on the lower level' },
        ],
        body: 'Tell us you came and we will have a small gift waiting for you.',
        qr: 'https://example.com/welcome',
        qrLabel: 'Say hello',
      },
    },
    {
      key: 'livestream-promo',
      name: 'Watch Live Online',
      description: 'Live stream promo with scan-to-watch QR.',
      tags: ['livestream', 'online'],
      recipe: 'promoBurst',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        eyebrow: 'CANNOT MAKE IT IN?',
        title: 'Watch Live Sundays',
        titleSize: 0.13,
        body: 'Both services stream at 9 and 11, plus the full sermon archive.',
        qr: 'https://example.com/live',
        qrLabel: 'Watch now',
        footer: 'GRACECHAPEL.ORG/LIVE',
      },
    },
    {
      key: 'food-drive',
      name: 'Food Drive Total',
      description: 'Portrait running total against the seasonal goal.',
      tags: ['outreach', 'food'],
      recipe: 'bigNumber',
      orientation: 'portrait',
      spec: {
        palette: 'espresso',
        eyebrow: 'FALL FOOD DRIVE',
        value: '4,820',
        valueSize: 0.26,
        label: 'Meals collected so far',
        body: 'Goal is 10,000 by Thanksgiving. Drop bags in the lobby bins.',
        footer: 'MOST NEEDED: RICE, BEANS, CANNED TUNA',
      },
    },
    {
      key: 'wedding-notice',
      name: 'Wedding Notice',
      description: 'Ceremony time and reception details for guests.',
      tags: ['wedding', 'notice'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'rose',
        display: 'playfair',
        eyebrow: 'PLEASE JOIN US',
        title: 'Emily & Daniel',
        titleSize: 0.12,
        body: 'Saturday, September 12 at 4 PM in the Sanctuary. Reception follows in Fellowship Hall.',
        footer: 'SANCTUARY CLOSED AFTER 2 PM SATURDAY',
      },
    },
    {
      key: 'memorial-notice',
      name: 'Memorial Service',
      description: 'Quiet light-palette notice for a funeral service.',
      tags: ['memorial', 'notice'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'mono',
        display: 'playfair',
        gradient: false,
        eyebrow: 'IN LOVING MEMORY',
        title: 'Margaret Ellis',
        titleSize: 0.11,
        body: 'Memorial service Thursday at 11 AM in the Sanctuary. Lunch to follow. All are welcome.',
        footer: '1938 - 2026',
      },
    },
    {
      key: 'pastor-quote',
      name: 'Pastor Message Quote',
      description: 'Pull quote lifted from Sunday\'s sermon.',
      tags: ['sermon', 'quote'],
      recipe: 'quoteCard',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        quote: 'Grace is not a reward for the strong. It is a rescue for the weary.',
        quoteSize: 0.055,
        author: 'Pastor Dan Whitfield',
        footer: 'FROM SUNDAY\'S MESSAGE  |  ROOTED, WEEK THREE',
      },
    },
    {
      key: 'offering-breakdown',
      name: 'Where Giving Goes',
      description: 'Four-tile breakdown of annual offering spend.',
      tags: ['giving', 'stats'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'paper',
        title: 'Where Your Giving Goes',
        subtitle: 'TWELVE MONTHS ENDING JUNE 2026',
        tiles: [
          { label: 'Ministry and staff', value: '46%' },
          { label: 'Missions and outreach', value: '22%', accent: '#15803d' },
          { label: 'Kids and youth', value: '18%' },
          { label: 'Building and care', value: '14%' },
        ],
        footer: 'FULL ANNUAL REPORT AT THE WELCOME DESK',
      },
    },
    {
      key: 'christmas-eve',
      name: 'Christmas Eve Services',
      description: 'Portrait poster for the three candlelight services.',
      tags: ['christmas', 'seasonal'],
      recipe: 'promoBurst',
      orientation: 'portrait',
      spec: {
        palette: 'crimson',
        eyebrow: 'DECEMBER 24',
        title: 'Christmas Eve',
        titleSize: 0.13,
        body: 'Candlelight and carols at 3, 5 and 7 PM. Childcare at the 3 PM service.',
        footer: 'DOORS OPEN THIRTY MINUTES EARLY',
      },
    },
    {
      key: 'easter-services',
      name: 'Easter Sunday',
      description: 'Sunrise and morning Easter service times.',
      tags: ['easter', 'seasonal'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'amber',
        eyebrow: 'EASTER SUNDAY',
        title: 'He Is Risen',
        body: 'Sunrise service at 6:30 in the field, then 9 and 11 in the Sanctuary.',
        cta: 'Bring the whole family',
        scrim: 60,
      },
    },
    {
      key: 'church-life-photos',
      name: 'Life at Our Church',
      description: 'Three photo frames of recent church life.',
      tags: ['photos', 'community'],
      recipe: 'photoStrip',
      orientation: 'landscape',
      spec: {
        palette: 'teal',
        title: 'Life at Grace Chapel',
        subtitle: 'SUMMER 2026',
        frames: 3,
        captions: [
          'Serve Day at Millbrook Park',
          'Middle school camp week',
          'Sunday morning in the Loft',
        ],
        footer: 'TAG YOUR PHOTOS #GRACECHAPEL',
      },
    },
    {
      key: 'summer-camp',
      name: 'Summer Camp Rates',
      description: 'Three camp tiers by age with a sign-up QR.',
      tags: ['camp', 'youth'],
      recipe: 'priceCards',
      orientation: 'landscape',
      spec: {
        palette: 'violet',
        title: 'Summer Camp 2026',
        subtitle: 'Camp Winona  |  June 15 - 20',
        cards: [
          { name: 'KIDS CAMP', price: '$185', desc: 'Grades 3-5, three nights, all meals included.' },
          { name: 'MIDDLE SCHOOL', price: '$245', desc: 'Grades 6-8, five nights, lake and ropes course.', featured: true },
          { name: 'HIGH SCHOOL', price: '$265', desc: 'Grades 9-12, five nights, evening worship.' },
        ],
        qr: 'https://example.com/camp',
        qrLabel: 'Register',
        footer: 'SCHOLARSHIPS AVAILABLE - ASK ANY LEADER',
      },
    },
  ],
}
