/* Education pack — schools, colleges and campuses.
 *
 * Sample school throughout: Northgate Academy. Names, rooms and prices are
 * plausible placeholders an operator edits in one pass; nothing here reads as
 * a blank to fill in.
 */

export default {
  category: 'education',
  name: 'Education',
  description: 'Timetables, exam boards, canteen menus and campus notices for schools and colleges.',
  icon: '🎓',
  templates: [
    // ── welcome and identity ────────────────────────────────────────────────
    {
      key: 'campus-welcome',
      name: 'Campus Welcome',
      description: 'Full-bleed welcome board for the main entrance.',
      tags: ['welcome', 'reception'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        eyebrow: 'WELCOME TO',
        title: 'Northgate Academy',
        titleSize: 0.12,
        body: 'Reception is straight ahead. All visitors sign in and collect a lanyard.',
        cta: 'Sign in here',
        scrim: 66,
      },
    },
    {
      key: 'campus-life',
      name: 'Campus Life Gallery',
      description: 'Three photo frames with captions from the term.',
      tags: ['gallery', 'community'],
      recipe: 'photoStrip',
      orientation: 'landscape',
      spec: {
        palette: 'mono',
        title: 'Life at Northgate',
        subtitle: 'Autumn term highlights',
        frames: 3,
        captions: ['Science Fair 2026', 'Sports Day on the top field', 'Year 11 art exhibition'],
        footer: 'MORE PHOTOS ON THE SCHOOL NEWSLETTER',
      },
    },
    {
      key: 'principal-message',
      name: 'Principal Message',
      description: 'A short word from the head, set as a pull quote.',
      tags: ['leadership', 'quote'],
      recipe: 'quoteCard',
      orientation: 'landscape',
      spec: {
        palette: 'paper',
        quote: 'A school is judged by how its quietest student is treated.',
        quoteSize: 0.058,
        author: 'DR HELEN MARSH, PRINCIPAL',
      },
    },
    {
      key: 'quote-of-day',
      name: 'Quote of the Day',
      description: 'Rotating motivational quote for corridors and atriums.',
      tags: ['quote', 'daily'],
      recipe: 'quoteCard',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        quote: 'The expert in anything was once a beginner.',
        author: 'HELEN HAYES',
        footer: 'QUOTE OF THE DAY',
      },
    },

    // ── timetables and schedules ────────────────────────────────────────────
    {
      key: 'class-timetable',
      name: 'Class Timetable',
      description: 'One year group’s day, period by period, with rooms.',
      tags: ['timetable', 'lessons'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        title: 'Year 10 Timetable',
        subtitle: 'MONDAY',
        colTime: 'TIME',
        colName: 'SUBJECT',
        colMeta: 'ROOM',
        rows: [
          ['08:45', 'Registration', 'Tutor Base 12'],
          ['09:00', 'Mathematics', 'Room B14'],
          ['10:00', 'English Literature', 'Room A07'],
          ['11:15', 'Chemistry', 'Lab 3'],
          ['12:15', 'Lunch', 'Dining Hall'],
          ['13:15', 'History', 'Room C21'],
          ['14:15', 'Physical Education', 'Sports Hall'],
        ],
      },
    },
    {
      key: 'exam-schedule',
      name: 'Exam Schedule',
      description: 'Week one of the exam season with halls listed.',
      tags: ['exams', 'schedule'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'crimson',
        title: 'Summer Exams',
        subtitle: 'WEEK ONE',
        colTime: 'DATE',
        colName: 'PAPER',
        colMeta: 'HALL',
        rows: [
          ['Mon 08', 'Maths Paper 1', 'Main Hall'],
          ['Tue 09', 'Biology Paper 2', 'Main Hall'],
          ['Wed 10', 'English Language', 'Sports Hall'],
          ['Thu 11', 'Geography Paper 1', 'Main Hall'],
          ['Fri 12', 'French Listening', 'Language Suite'],
          ['Mon 15', 'Physics Paper 2', 'Main Hall'],
        ],
        footer: 'ARRIVE 20 MINUTES BEFORE EVERY PAPER',
      },
    },
    {
      key: 'term-dates',
      name: 'Term Dates',
      description: 'Key dates for the academic year on one board.',
      tags: ['calendar', 'term'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'forest',
        title: 'Term Dates 2026/27',
        subtitle: 'KEY DATES',
        colTime: 'DATE',
        colName: 'EVENT',
        colMeta: 'NOTES',
        rows: [
          ['02 SEP', 'Autumn term begins', 'Years 7 and 12 only'],
          ['24 OCT', 'Half term closes', 'Return 03 November'],
          ['19 DEC', 'Autumn term ends', '12:30 finish'],
          ['06 JAN', 'Spring term begins', 'Full timetable'],
          ['13 FEB', 'Half term closes', 'Return 23 February'],
          ['27 MAR', 'Spring term ends', '12:30 finish'],
          ['20 APR', 'Summer term begins', 'Exam season'],
        ],
        footer: 'INSET DAYS: 01 SEPTEMBER AND 22 JUNE',
      },
    },
    {
      key: 'library-hours',
      name: 'Library Hours',
      description: 'Opening times and help desk cover for the week.',
      tags: ['library', 'hours'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'paper',
        title: 'Library Opening Hours',
        subtitle: 'TERM TIME',
        colTime: 'DAY',
        colName: 'OPEN',
        colMeta: 'HELP DESK',
        rows: [
          ['MON', '08:00 - 17:30', 'Full staffing'],
          ['TUE', '08:00 - 17:30', 'Full staffing'],
          ['WED', '08:00 - 16:00', 'Full staffing'],
          ['THU', '08:00 - 18:30', 'Study club'],
          ['FRI', '08:00 - 16:00', 'Self service'],
          ['SAT', '09:00 - 12:00', 'Sixth form only'],
        ],
        footer: 'SILENT STUDY ON THE MEZZANINE AT ALL TIMES',
      },
    },
    {
      key: 'bus-routes',
      name: 'Home Time Buses',
      description: 'Departure times, routes and bay numbers.',
      tags: ['transport', 'buses'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'steel',
        title: 'Home Time Buses',
        subtitle: 'MONDAY TO FRIDAY',
        colTime: 'DEPART',
        colName: 'ROUTE',
        colMeta: 'BAY',
        rows: [
          ['15:20', 'R1 Northgate to Millfield', 'Bay 1'],
          ['15:20', 'R2 Northgate to Ashcombe', 'Bay 2'],
          ['15:25', 'R4 Northgate to Kirby Green', 'Bay 3'],
          ['15:30', 'R7 Northgate to Redhill Estate', 'Bay 4'],
          ['16:40', 'Late bus, study club only', 'Bay 1'],
          ['17:45', 'Late bus, fixtures only', 'Bay 1'],
        ],
        footer: 'QUEUE BEHIND THE YELLOW LINE',
      },
    },
    {
      key: 'sports-results',
      name: 'Fixture Results',
      description: 'Last week’s scores across every squad.',
      tags: ['sport', 'results'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'crimson',
        title: 'Fixture Results',
        subtitle: 'LAST WEEK',
        colTime: 'DAY',
        colName: 'FIXTURE',
        colMeta: 'RESULT',
        display: 'oswald',
        rows: [
          ['MON', 'U15 Football v Ashcombe', 'Won 3-1'],
          ['TUE', 'U14 Netball v St Brides', 'Won 28-19'],
          ['WED', '1st XI Hockey v Kirby Green', 'Drew 2-2'],
          ['THU', 'U16 Rugby v Redhill', 'Lost 12-17'],
          ['FRI', 'Senior Basketball v Ashcombe', 'Won 54-41'],
          ['SAT', 'Cross Country, District Meet', '2nd of 9'],
        ],
        footer: 'NEXT HOME FIXTURE: SATURDAY 10:30',
      },
    },

    // ── catering ────────────────────────────────────────────────────────────
    {
      key: 'canteen-menu',
      name: 'Canteen Menu',
      description: 'Hot line and grab-and-go with prices.',
      tags: ['canteen', 'menu'],
      recipe: 'menuBoard',
      orientation: 'landscape',
      spec: {
        palette: 'forest',
        title: 'Today at the Canteen',
        subtitle: 'WEDNESDAY',
        qr: 'https://example.com/canteen',
        qrLabel: 'Allergen info',
        sections: [
          {
            name: 'HOT LINE',
            items: [
              ['Chicken and Leek Pie', '2.80', 'Mash and green beans'],
              ['Veggie Chilli Bowl', '2.60', 'Brown rice, sour cream, tortilla chips'],
              ['Margherita Pizza Slice', '2.20', 'Add pepperoni for 40p'],
              ['Katsu Curry', '3.00', 'Chicken or sweet potato, sticky rice'],
              ['Jacket Potato', '2.40', 'Beans, cheese or tuna mayo'],
            ],
          },
          {
            name: 'GRAB AND GO',
            items: [
              ['Chicken Wrap', '2.50', 'Salad and light mayo'],
              ['Ham Salad Baguette', '2.30'],
              ['Fruit Pot', '1.20', 'Melon, grape and berries'],
              ['Oat Flapjack', '1.00'],
            ],
          },
        ],
      },
    },
    {
      key: 'breakfast-menu',
      name: 'Breakfast Club Menu',
      description: 'Single-column morning menu for the dining hall door.',
      tags: ['canteen', 'breakfast'],
      recipe: 'menuBoard',
      orientation: 'portrait',
      spec: {
        palette: 'espresso',
        title: 'Breakfast Club',
        subtitle: '07:30 - 08:30',
        footer: 'PAY WITH YOUR STUDENT CARD',
        sections: [
          {
            name: 'MORNING',
            items: [
              ['Porridge with Honey', '1.20'],
              ['Bacon Roll', '1.80'],
              ['Toast and Jam', '0.90'],
            ],
          },
          {
            name: 'DRINKS',
            items: [
              ['Hot Chocolate', '1.00'],
              ['Orange Juice', '0.90'],
              ['Cold Milk', '0.60'],
            ],
          },
        ],
      },
    },
    {
      key: 'club-signups',
      name: 'Club Sign-Ups',
      description: 'Lunchtime and after-school clubs with days and rooms.',
      tags: ['clubs', 'enrichment'],
      recipe: 'menuBoard',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        title: 'Clubs and Societies',
        subtitle: 'AUTUMN TERM',
        qr: 'https://example.com/clubs',
        qrLabel: 'Sign up',
        sections: [
          {
            name: 'LUNCHTIME',
            items: [
              ['Chess Club', 'MON', 'Room B14 with Mr Hale'],
              ['Debating Society', 'TUE', 'Room A07'],
              ['Coding Club', 'WED', 'ICT Suite 2'],
              ['Chamber Choir', 'THU', 'Music Room 1'],
            ],
          },
          {
            name: 'AFTER SCHOOL',
            items: [
              ['Football, Years 7 to 9', 'MON'],
              ['Drama Workshop', 'TUE'],
              ['Robotics', 'WED'],
              ['Art Club', 'THU'],
            ],
          },
        ],
      },
    },

    // ── events ──────────────────────────────────────────────────────────────
    {
      key: 'open-day',
      name: 'Open Day',
      description: 'Photo-and-message hero for prospective families.',
      tags: ['event', 'admissions'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        eyebrow: 'SATURDAY 12 OCTOBER',
        title: 'Open Day',
        body: 'Tours every thirty minutes from ten. Meet teachers, see the labs, stay for lunch.',
        cta: 'Book a tour',
        flip: true,
        qr: 'https://example.com/openday',
        qrLabel: 'Book a place',
      },
    },
    {
      key: 'science-fair',
      name: 'Science Fair Poster',
      description: 'Loud portrait promo for the annual science fair.',
      tags: ['event', 'science'],
      recipe: 'promoBurst',
      orientation: 'portrait',
      spec: {
        palette: 'violet',
        eyebrow: 'THURSDAY 14 MARCH',
        title: 'Science Fair',
        titleSize: 0.085,
        body: 'Sixty student projects. Judging at two.',
        footer: 'MAIN HALL - ALL YEAR GROUPS WELCOME',
      },
    },
    {
      key: 'sports-day',
      name: 'Sports Day',
      description: 'Photo overlay announcing the summer athletics day.',
      tags: ['event', 'sport'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'amber',
        eyebrow: 'FRIDAY 20 JUNE',
        title: 'Summer Sports Day',
        body: 'Track events from ten on the top field. Parents welcome, bring a chair.',
        cta: 'Programme',
        scrim: 58,
      },
    },
    {
      key: 'parents-evening',
      name: 'Parents Evening',
      description: 'Booking notice with a scannable slot link.',
      tags: ['parents', 'event'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        eyebrow: 'YEAR 9 PARENTS',
        title: 'Parents Evening',
        titleSize: 0.12,
        body: 'Thursday 6 November, four until seven. Five minute slots with every subject teacher.',
        qr: 'https://example.com/bookings',
        qrLabel: 'Book slots',
      },
    },
    {
      key: 'graduation-countdown',
      name: 'Graduation Countdown',
      description: 'One enormous number counting down to the ceremony.',
      tags: ['countdown', 'graduation'],
      recipe: 'bigNumber',
      orientation: 'portrait',
      spec: {
        palette: 'violet',
        eyebrow: 'CLASS OF 2027',
        value: '128',
        label: 'DAYS TO GRADUATION',
        body: 'Gowns must be ordered by 12 May. Guest tickets go live at half term.',
      },
    },

    // ── recognition ─────────────────────────────────────────────────────────
    {
      key: 'honour-roll',
      name: 'Honour Roll',
      description: 'Termly commendations listed by name and form.',
      tags: ['awards', 'students'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'amber',
        title: 'Honour Roll, Autumn Term',
        entries: [
          ['Amara Okafor', '10B'],
          ['Daniel Reyes', '9C'],
          ['Sophie Lindqvist', '11A'],
          ['Yusuf Rahman', '8D'],
          ['Grace Mbeki', '12S'],
          ['Tomas Novak', '9A'],
          ['Priya Nair', '10F'],
          ['Ethan Caldwell', '7B'],
          ['Lucia Ferrari', '11C'],
          ['Noah Kimani', '8A'],
          ['Hannah Weiss', '12S'],
          ['Oliver Tran', '7E'],
        ],
        footer: 'NOMINATED BY THEIR SUBJECT TEACHERS',
      },
    },
    {
      key: 'student-of-month',
      name: 'Student of the Month',
      description: 'Portrait photo beside a short citation.',
      tags: ['awards', 'students'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'rose',
        eyebrow: 'STUDENT OF THE MONTH',
        title: 'Amara Okafor',
        titleSize: 0.09,
        body: 'Year 10. Outstanding physics coursework and two terms of peer mentoring in the library.',
        cta: 'Congratulations',
      },
    },

    // ── numbers ─────────────────────────────────────────────────────────────
    {
      key: 'attendance-stats',
      name: 'Attendance Stats',
      description: 'Four attendance tiles for the current week.',
      tags: ['stats', 'attendance'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'teal',
        title: 'Attendance This Week',
        subtitle: 'WEEK 6',
        tiles: [
          { label: 'WHOLE SCHOOL', value: '96.4%', sub: 'Target is 97 percent' },
          { label: 'YEAR 7', value: '98.1%', sub: 'Best year group', accent: '#22c55e' },
          { label: 'YEAR 11', value: '94.2%', sub: 'Down 0.8 this week', accent: '#f97316' },
          { label: 'LATE MARKS', value: '37', sub: 'Gates close at 08:45' },
        ],
        footer: 'EVERY LESSON COUNTS - BE ON TIME',
      },
    },
    {
      key: 'reading-challenge',
      name: 'Reading Challenge',
      description: 'Progress tiles for the whole-school reading target.',
      tags: ['library', 'stats'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'sand',
        title: 'Reading Challenge',
        subtitle: 'SPRING TERM',
        tiles: [
          { label: 'BOOKS FINISHED', value: '2,148', sub: 'Target 2,500 by Easter' },
          { label: 'TOP YEAR GROUP', value: 'Year 8', sub: '412 books this term' },
          { label: 'MINUTES READ', value: '61,300', sub: 'Logged in the app' },
          { label: 'NEW MEMBERS', value: '184', sub: 'Library cards issued' },
        ],
        footer: 'LOG YOUR MINUTES AT THE LIBRARY DESK',
      },
    },

    // ── directories ─────────────────────────────────────────────────────────
    {
      key: 'teacher-directory',
      name: 'Teacher Directory',
      description: 'Staff names and their teaching rooms.',
      tags: ['staff', 'directory'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'mono',
        title: 'Staff Directory',
        entries: [
          ['Dr Helen Marsh, Head', 'D1'],
          ['Mr Alan Hale, Maths', 'B14'],
          ['Ms Ruth Odeyemi, English', 'A07'],
          ['Mr Ben Castillo, Physics', 'Lab 3'],
          ['Mrs Sara Novak, Chemistry', 'Lab 1'],
          ['Mr Femi Adeyemi, Biology', 'Lab 2'],
          ['Ms Clara Berg, History', 'C21'],
          ['Mr Owen Pryce, Geography', 'C18'],
          ['Mme Elise Duval, French', 'L4'],
          ['Mr Jack Rowe, PE', 'Sports Hall'],
          ['Ms Nia Thomas, Art', 'Art 3'],
          ['Mr Paul Grant, Music', 'M1'],
        ],
        footer: 'STAFF ARE AVAILABLE AT BREAK AND LUNCH',
      },
    },
    {
      key: 'room-directory',
      name: 'Room Directory',
      description: 'Wayfinding list of offices, blocks and facilities.',
      tags: ['wayfinding', 'directory'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'clinical',
        title: 'Where to Find Us',
        entries: [
          ['Reception and Visitors', 'Ground'],
          ['Attendance Office', 'G04'],
          ['Finance and Fees', 'G09'],
          ['Medical Room', 'G12'],
          ['Library and Study Hall', 'First floor'],
          ['Science Labs 1 to 4', 'Second floor'],
          ['ICT Suites', 'B Block'],
          ['Design Technology', 'DT Workshop'],
          ['Art and Photography', 'Art Block'],
          ['Music Practice Rooms', 'M Corridor'],
          ['Sports Hall and Gym', 'South Wing'],
          ['Sixth Form Centre', 'North Wing'],
        ],
        footer: 'ASK ANY MEMBER OF STAFF IN A BLUE LANYARD',
      },
    },

    // ── operations ──────────────────────────────────────────────────────────
    {
      key: 'fire-drill',
      name: 'Fire Drill Steps',
      description: 'Five numbered steps for the evacuation procedure.',
      tags: ['safety', 'drill'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'crimson',
        title: 'Fire Drill Procedure',
        steps: [
          ['Stop and listen', 'Leave work where it is, do not collect bags or coats'],
          ['Walk to the nearest exit', 'Follow the green signs, no running and no talking'],
          ['Line up on the tennis courts', 'Find your tutor group marker and stand in silence'],
          ['Answer your name', 'Tutors take the register and report to the fire marshal'],
          ['Wait for the all clear', 'Only the senior leader on duty sends you back inside'],
        ],
        footer: 'ASSEMBLY POINT: TENNIS COURTS',
      },
    },
    {
      key: 'exam-hall-rules',
      name: 'Exam Hall Rules',
      description: 'Numbered rules displayed outside the exam hall.',
      tags: ['exams', 'rules'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'charcoal',
        title: 'Exam Hall Rules',
        steps: [
          ['Arrive twenty minutes early', 'Queue outside in silence with your candidate number ready'],
          ['Bags and phones outside', 'Leave everything on the racks by the corridor door'],
          ['Clear pencil case only', 'Black pen, pencil, ruler and an approved calculator'],
          ['Raise your hand for help', 'Do not leave your seat once the paper has started'],
          ['Stay until dismissed', 'Invigilators collect every script before anyone stands'],
        ],
        footer: 'GOOD LUCK FROM ALL OF US',
      },
    },
    {
      key: 'student-wifi',
      name: 'Student Wi-Fi',
      description: 'Network, password and a QR to join.',
      tags: ['wifi', 'ict'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        title: 'Student Wi-Fi',
        fields: [
          { label: 'NETWORK', value: 'NGA-Student' },
          { label: 'PASSWORD', value: 'Learn2026!', mono: true },
          { label: 'HELP', value: 'ICT Office, Room D2' },
        ],
        qr: 'https://example.com/wifi',
        qrLabel: 'Connect',
        body: 'Fair use applies. Streaming and gaming sites are blocked during lesson time.',
      },
    },
    {
      key: 'fees-deadline',
      name: 'Fees Deadline',
      description: 'Portrait payment reminder with a pay-online code.',
      tags: ['fees', 'notice'],
      recipe: 'announcement',
      orientation: 'portrait',
      spec: {
        palette: 'charcoal',
        eyebrow: 'AUTUMN TERM 2026',
        title: 'Fees Due Sept 30',
        titleSize: 0.085,
        body: 'Pay online or at the finance office. Instalment plans available on request.',
        qr: 'https://example.com/fees',
        qrLabel: 'Pay online',
      },
    },
    {
      key: 'tuition-plans',
      name: 'Tuition Plans',
      description: 'Three termly fee options as offer cards.',
      tags: ['fees', 'admissions'],
      recipe: 'priceCards',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        title: 'Termly Fees 2026/27',
        subtitle: 'Per student, per term',
        cards: [
          { name: 'DAY PLACE', price: '4,250', desc: 'Lessons, lunch and all core trips' },
          { name: 'DAY PLUS CLUBS', price: '4,690', desc: 'Adds after school clubs and the late bus', featured: true },
          { name: 'SIXTH FORM', price: '4,880', desc: 'Includes the university guidance programme' },
        ],
        qr: 'https://example.com/fees',
        qrLabel: 'Fee schedule',
      },
    },
  ],
}
