export default {
  category: 'gym',
  name: 'Gym',
  description: 'Class timetables, membership offers, rules and motivation for gyms, studios and leisure centres.',
  icon: '🏋️',
  templates: [
    {
      key: 'class-timetable',
      name: 'Class Timetable',
      description: 'Studio classes for today with times and rooms.',
      tags: ['classes', 'timetable'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        title: 'Today at Ironworks',
        subtitle: 'Tuesday classes',
        colTime: 'TIME',
        colName: 'CLASS',
        colMeta: 'STUDIO',
        rows: [
          ['06:15', 'Sunrise HIIT', 'Studio 1'],
          ['07:30', 'Spin Express', 'Cycle Room'],
          ['09:00', 'Reformer Pilates', 'Studio 2'],
          ['12:15', 'Express Circuit', 'Main Floor'],
          ['17:45', 'Boxfit', 'Studio 1'],
          ['18:45', 'Strength Foundations', 'Free Weights'],
          ['19:45', 'Yin Yoga', 'Studio 2'],
        ],
        qr: 'https://example.com/timetable',
        qrLabel: 'Book a class',
        footer: 'Book up to seven days ahead on the app',
      },
    },
    {
      key: 'membership-plans',
      name: 'Membership Plans',
      description: 'Three membership tiers with monthly prices.',
      tags: ['membership', 'pricing'],
      recipe: 'priceCards',
      orientation: 'landscape',
      spec: {
        palette: 'charcoal',
        title: 'Membership',
        subtitle: 'No joining fee this month',
        cards: [
          { name: 'Off Peak', price: '£24.99', desc: 'Weekdays until 4pm' },
          { name: 'Full Access', price: '£34.99', desc: 'All hours, all classes', featured: true },
          { name: 'Premium', price: '£44.99', desc: 'Adds pool, spa and guest passes' },
        ],
        qr: 'https://example.com/join',
        qrLabel: 'Join online',
        footer: 'Rolling monthly. Cancel with 30 days notice.',
      },
    },
    {
      key: 'personal-training',
      name: 'Personal Training Promo',
      description: 'Split promo for one to one coaching packages.',
      tags: ['training', 'promo'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'steel',
        eyebrow: 'Personal training',
        title: 'Train With A Coach',
        titleSize: 0.1,
        body: 'Six sessions, a written plan and a monthly progress check with your own trainer.',
        cta: 'Free consultation at reception',
        qr: 'https://example.com/personal-training',
        qrLabel: 'See packages',
      },
    },
    {
      key: 'join-now-offer',
      name: 'Join Now Offer',
      description: 'Portrait poster for a half price first month.',
      tags: ['offer', 'join'],
      recipe: 'promoBurst',
      orientation: 'portrait',
      spec: {
        palette: 'crimson',
        eyebrow: 'Limited offer',
        title: 'First Month Half Price',
        titleSize: 0.13,
        body: 'Join before the end of the month and pay 17.50 for your first four weeks.',
        code: 'HALF25',
        qr: 'https://example.com/join',
        qrLabel: 'Join in two minutes',
        footer: 'New members only. Twelve month minimum term.',
      },
    },
    {
      key: 'gym-floor-rules',
      name: 'Gym Floor Rules',
      description: 'Five house rules for the training floor.',
      tags: ['rules', 'etiquette'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        title: 'Gym Floor Rules',
        steps: [
          ['Wipe Down Kit', 'Spray and wipe every bench and machine after use.'],
          ['Re-Rack Weights', 'Plates and dumbbells back on the rack, every time.'],
          ['Share The Machines', 'Twenty minutes max on cardio when the floor is busy.'],
          ['Bags In Lockers', 'Keep walkways and racks clear of bags and coats.'],
          ['Ask For A Spot', 'Staff in red shirts are happy to spot or advise.'],
        ],
        footer: 'Thanks for keeping the floor safe for everyone',
      },
    },
    {
      key: 'equipment-maintenance',
      name: 'Equipment Maintenance Notice',
      description: 'Out of service notice for a piece of kit.',
      tags: ['notice', 'maintenance'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'amber',
        eyebrow: 'Maintenance notice',
        title: 'Squat Rack 3 Closed',
        titleSize: 0.12,
        body: 'Servicing until Thursday at 5pm. Racks one, two and four are open as usual.',
        footer: 'Sorry for the disruption. Maintenance team.',
      },
    },
    {
      key: 'member-of-the-month',
      name: 'Member Of The Month',
      description: 'Photo tribute to a standout member.',
      tags: ['members', 'community'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        eyebrow: 'Member of the month',
        title: 'Priya Raman',
        titleSize: 0.13,
        body: 'Down nine kilos, up forty on her deadlift, and never misses a 6am class.',
        cta: 'Nominate next month at reception',
        anchor: 'bottom',
        scrim: 68,
      },
    },
    {
      key: 'transformation-challenge',
      name: 'Transformation Challenge',
      description: 'Sign up burst for the eight week challenge.',
      tags: ['challenge', 'promo'],
      recipe: 'promoBurst',
      orientation: 'landscape',
      spec: {
        palette: 'violet',
        eyebrow: 'Eight week challenge',
        title: 'The Eight Week Shred',
        titleSize: 0.15,
        body: 'Body scan, coached plan and weekly check ins. The winner takes a free year.',
        code: 'SHRED8',
        qr: 'https://example.com/challenge',
        qrLabel: 'Enter the challenge',
        footer: 'Entries close Sunday. Twenty places only.',
      },
    },
    {
      key: 'opening-hours',
      name: 'Opening Hours',
      description: 'Gym and pool hours across the week.',
      tags: ['hours', 'info'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'forest',
        title: 'Opening Hours',
        colTime: 'DAY',
        colName: 'GYM',
        colMeta: 'POOL',
        rows: [
          ['Mon to Thu', '05:30 - 22:30', '06:00 - 22:00'],
          ['Friday', '05:30 - 21:30', '06:00 - 21:00'],
          ['Saturday', '07:00 - 20:00', '07:30 - 19:30'],
          ['Sunday', '08:00 - 20:00', '08:30 - 19:30'],
          ['Bank holidays', '08:00 - 18:00', '09:00 - 17:30'],
        ],
        footer: 'Last entry 45 minutes before close',
      },
    },
    {
      key: 'fuel-bar-menu',
      name: 'Fuel Bar Menu',
      description: 'Protein shakes, coffee and snacks with prices.',
      tags: ['menu', 'shakes'],
      recipe: 'menuBoard',
      orientation: 'landscape',
      spec: {
        palette: 'espresso',
        title: 'The Fuel Bar',
        subtitle: 'Made to order',
        columns: 2,
        sections: [
          {
            name: 'Shakes',
            items: [
              ['Whey Classic', '£4.50', '30g protein, banana, oats'],
              ['Berry Recovery', '£4.95', 'Mixed berries, yoghurt, honey'],
              ['Green Machine', '£5.25', 'Spinach, apple, ginger, lime'],
              ['Peanut Butter Cup', '£5.50', 'Cocoa, banana, peanut butter'],
            ],
          },
          {
            name: 'Coffee and Extras',
            items: [
              ['Flat White', '£3.20'],
              ['Cold Brew', '£3.60'],
              ['Protein Flapjack', '£2.40'],
              ['Overnight Oats', '£3.80'],
              ['Electrolyte Water', '£2.20'],
            ],
          },
        ],
        footer: 'Members save ten percent at the till',
      },
    },
    {
      key: 'shake-bar-portrait',
      name: 'Shake Bar Board',
      description: 'Single column shake and snack list for a portrait screen.',
      tags: ['menu', 'snacks'],
      recipe: 'menuBoard',
      orientation: 'portrait',
      spec: {
        palette: 'sand',
        title: 'Shakes and Snacks',
        subtitle: 'Order at the desk',
        columns: 1,
        sections: [
          {
            items: [
              ['Whey Classic', '£4.50'],
              ['Berry Recovery', '£4.95'],
              ['Green Machine', '£5.25'],
              ['Peanut Butter Cup', '£5.50'],
              ['Iced Americano', '£3.00'],
              ['Protein Flapjack', '£2.40'],
              ['Salted Nut Bar', '£2.20'],
              ['Electrolyte Water', '£2.20'],
            ],
          },
        ],
        footer: 'Ask about the post workout deal',
      },
    },
    {
      key: 'quote-discipline',
      name: 'Motivation: Discipline',
      description: 'Light pull quote on discipline for the studio wall.',
      tags: ['motivation', 'quote'],
      recipe: 'quoteCard',
      orientation: 'landscape',
      spec: {
        palette: 'mono',
        quote: 'Discipline is choosing what you want most over what you want right now.',
        quoteSize: 0.05,
        author: 'Marcus Hale, Head of Training',
        display: 'playfair',
      },
    },
    {
      key: 'quote-consistency',
      name: 'Motivation: Consistency',
      description: 'Dark pull quote about showing up often.',
      tags: ['motivation', 'quote'],
      recipe: 'quoteCard',
      orientation: 'landscape',
      spec: {
        palette: 'charcoal',
        quote: 'Small sessions, repeated, beat big sessions, skipped.',
        quoteSize: 0.058,
        author: 'The Ironworks coaching team',
        footer: 'Twenty minutes still counts',
      },
    },
    {
      key: 'workout-of-the-day',
      name: 'Workout Of The Day',
      description: 'Numbered circuit with reps and coaching notes.',
      tags: ['workout', 'training'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        title: 'Workout Of The Day',
        steps: [
          ['Row 500m', 'Steady pace, hold under 2:10 per 500.'],
          ['20 Goblet Squats', '16kg or 24kg. Chest tall, heels down.'],
          ['15 Push Ups', 'Drop to your knees if form slips.'],
          ['10 Burpees', 'Chest to the floor, jump at the top.'],
          ['Four Rounds', 'Rest ninety seconds between rounds.'],
        ],
        footer: 'Scale it back and ask a coach if unsure',
      },
    },
    {
      key: 'trainer-directory',
      name: 'Trainer Directory',
      description: 'Who is who on the floor and where to find them.',
      tags: ['trainers', 'directory'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        title: 'Meet The Trainers',
        entries: [
          ['Marcus Hale', 'Strength, Studio 1'],
          ['Priya Nair', 'Pilates, Studio 2'],
          ['Danny Okoro', 'Boxing, The Ring'],
          ['Sofia Marchetti', 'Spin, Cycle Room'],
          ['Tom Beckett', 'Rehab, Clinic Room'],
          ['Aisha Farid', 'Yoga, Studio 2'],
          ['Jonas Weiss', 'Olympic Lifting, Platform'],
          ['Elena Rossi', 'Nutrition, Desk 2'],
          ['Kai Thompson', 'HIIT, Main Floor'],
          ['Ruth Adeyemi', 'Swim Coaching, Pool'],
        ],
        footer: 'Book a free intro session at reception',
      },
    },
    {
      key: 'pool-spa-hours',
      name: 'Pool And Spa Hours',
      description: 'Swim, aqua class and sauna session times.',
      tags: ['pool', 'sauna'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'teal',
        title: 'Pool and Spa',
        subtitle: 'Daily sessions',
        colTime: 'TIME',
        colName: 'SESSION',
        colMeta: 'WHERE',
        rows: [
          ['06:00 - 09:00', 'Lane Swim', 'Main Pool'],
          ['09:30 - 10:15', 'Aqua Fit Class', 'Main Pool'],
          ['10:30 - 16:00', 'Open Swim', 'Main Pool'],
          ['12:00 - 21:00', 'Sauna and Steam', 'Spa Suite'],
          ['16:00 - 18:00', 'Junior Swim', 'Main Pool'],
          ['18:00 - 21:30', 'Lane Swim', 'Main Pool'],
        ],
        footer: 'Swim caps required in all lanes',
      },
    },
    {
      key: 'referral-programme',
      name: 'Referral Programme',
      description: 'Refer a friend and you both get a free month.',
      tags: ['referral', 'offer'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'rose',
        eyebrow: 'Referral programme',
        title: 'Both Get A Free Month',
        titleSize: 0.095,
        body: 'Your friend joins, you both get four weeks free. Refer as many as you like.',
        cta: 'Referral cards at reception',
        flip: true,
        qr: 'https://example.com/refer',
        qrLabel: 'Refer a friend',
      },
    },
    {
      key: 'app-download',
      name: 'App Download',
      description: 'Card explaining the member app with a scan code.',
      tags: ['app', 'qr'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        title: 'Get The Ironworks App',
        fields: [
          { label: 'Book classes', value: 'Up to seven days ahead' },
          { label: 'Door entry', value: 'Scan in with your phone' },
          { label: 'Member code', value: 'IRONWORKS', mono: true },
        ],
        body: 'Free on iOS and Android.',
        qr: 'https://example.com/app',
        qrLabel: 'Scan to install',
      },
    },
    {
      key: 'new-equipment',
      name: 'New Equipment Announcement',
      description: 'Announce new kit landing on the gym floor.',
      tags: ['equipment', 'news'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        eyebrow: 'Now on the floor',
        title: 'Six New Rowers',
        titleSize: 0.14,
        body: 'New rowing machines with live leaderboards are installed by the back window.',
        footer: 'Ask a coach for a two minute intro',
      },
    },
    {
      key: 'class-spotlight',
      name: 'Group Class Spotlight',
      description: 'Full bleed spotlight on one group class.',
      tags: ['classes', 'spotlight'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'crimson',
        eyebrow: 'Class spotlight',
        title: 'Boxfit Fridays',
        titleSize: 0.13,
        body: 'Forty five minutes of pads, bags and conditioning. Gloves provided, no experience needed.',
        cta: 'Fridays 18:30, Studio 1',
        anchor: 'bottom',
        scrim: 66,
        qr: 'https://example.com/classes/boxfit',
        qrLabel: 'Reserve a spot',
      },
    },
    {
      key: 'hydration-tip',
      name: 'Hydration Tip',
      description: 'Portrait health tip with a big daily water target.',
      tags: ['health', 'tip'],
      recipe: 'bigNumber',
      orientation: 'portrait',
      spec: {
        palette: 'teal',
        eyebrow: 'Health tip',
        value: '2.5L',
        valueSize: 0.28,
        label: 'Water a day',
        body: 'Fill up free at the fountains by the changing rooms. Sip before you feel thirsty.',
        footer: 'Filtered water on every floor',
      },
    },
    {
      key: 'guest-pass',
      name: 'Guest Pass Promo',
      description: 'Members bring a friend on a free day pass.',
      tags: ['guest', 'offer'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'sand',
        eyebrow: 'Guest passes',
        title: 'Bring A Friend Free',
        titleSize: 0.13,
        body: 'Every member gets two free day passes a month. Add your guest on the app.',
        qr: 'https://example.com/guest-pass',
        qrLabel: 'Add a guest',
        footer: 'Guests must be 16 or over and sign in at reception',
      },
    },
    {
      key: 'gym-stats',
      name: 'Gym Stats',
      description: 'Four headline numbers about the club.',
      tags: ['stats', 'community'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'charcoal',
        title: 'Ironworks By The Numbers',
        subtitle: 'Updated this month',
        tiles: [
          { label: 'Members', value: '4,820', sub: 'Up 340 this year' },
          { label: 'Classes a week', value: '96', sub: 'Across three studios' },
          { label: 'Coaches', value: '18', sub: 'All Level 3 qualified', accent: '#f59e0b' },
          { label: 'Kilos lifted', value: '1.2M', sub: 'Tracked last month' },
        ],
        footer: 'Thanks for being part of it',
      },
    },
    {
      key: 'towel-locker-policy',
      name: 'Towel And Locker Policy',
      description: 'Locker rules and towel hire at a glance.',
      tags: ['policy', 'lockers'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'steel',
        title: 'Towels and Lockers',
        fields: [
          { label: 'Day lockers', value: 'Free, bring your own padlock' },
          { label: 'Overnight', value: 'Cut at 22:30, contents to lost property' },
          { label: 'Towel hire', value: '2 pounds at reception, 5 pound deposit' },
        ],
        body: 'Lost property is held for 14 days.',
      },
    },
    {
      key: 'results-wall',
      name: 'Results Wall',
      description: 'Three member results with photo frames and captions.',
      tags: ['results', 'community'],
      recipe: 'photoStrip',
      orientation: 'landscape',
      spec: {
        palette: 'espresso',
        title: 'Twelve Week Results',
        subtitle: 'Real members, real programmes',
        frames: 3,
        captions: ['Dan, down 11kg', 'Meera, first pull up', 'Chris, 140kg deadlift'],
        footer: 'Your before photo starts on day one',
      },
    },
    {
      key: 'member-milestone',
      name: 'Member Milestone',
      description: 'Portrait big number celebrating the member count.',
      tags: ['milestone', 'community'],
      recipe: 'bigNumber',
      orientation: 'portrait',
      spec: {
        palette: 'amber',
        eyebrow: 'Milestone',
        value: '5,000',
        valueSize: 0.24,
        label: 'Members and counting',
        body: 'You train at the biggest independent gym in the city. Thank you for that.',
        footer: 'Ironworks Gym, open since 2011',
      },
    },
  ],
}
