/* Healthcare template pack.
 *
 * Waiting rooms, clinic corridors and pharmacy counters. Copy is written for a
 * fictional but plausible site (Riverside Family Health) so an operator can put
 * a board on screen unedited and only swap names, rooms and numbers.
 * Light palettes carry most of the set — clinical spaces read better bright —
 * with a few dark boards for wayfinding, promos and quiet notices.
 */
export default {
  category: 'healthcare',
  name: 'Healthcare',
  description: 'Waiting room boards, wait times, hygiene steps and clinic notices for practices, clinics and hospitals.',
  icon: '🏥',
  templates: [
    // ── welcome and orientation ──────────────────────────────────────────────
    {
      key: 'waiting-room-welcome',
      name: 'Waiting Room Welcome',
      description: 'Full-bleed welcome board for the main waiting area.',
      tags: ['welcome', 'waiting', 'lobby'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        eyebrow: 'RIVERSIDE FAMILY HEALTH',
        title: 'Welcome To Our Clinic',
        titleSize: 0.115,
        body: 'Please check in at the front desk. A team member will call your name shortly.',
        cta: 'CHECK IN AT DESK',
        scrim: 66,
      },
    },
    {
      key: 'wait-times',
      name: 'Current Wait Times',
      description: 'Live estimated wait per department in big-number tiles.',
      tags: ['waiting', 'status', 'queue'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'clinical',
        title: 'Current Wait Times',
        subtitle: 'UPDATED EVERY 15 MINUTES',
        tiles: [
          { label: 'URGENT CARE', value: '25 min', sub: '12 patients waiting' },
          { label: 'FAMILY MEDICINE', value: '10 min', sub: 'Running on schedule', accent: '#16a34a' },
          { label: 'RADIOLOGY', value: '40 min', sub: 'X-ray and ultrasound' },
          { label: 'BLOOD DRAW', value: '5 min', sub: 'Walk-ins welcome', accent: '#16a34a' },
        ],
        footer: 'TIMES ARE ESTIMATES AND MAY CHANGE',
      },
    },
    {
      key: 'check-in-steps',
      name: 'How To Check In',
      description: 'Portrait pillar poster with the five check-in steps.',
      tags: ['check-in', 'steps', 'reception'],
      recipe: 'stepList',
      orientation: 'portrait',
      spec: {
        palette: 'mono',
        title: 'Check In Here',
        steps: [
          ['Take a ticket', 'Kiosk by the main door.'],
          ['Show photo ID', 'And your insurance card.'],
          ['Confirm your details', 'Tell us if anything changed.'],
          ['Watch the screen', 'Your number is called here.'],
          ['Go to the room shown', 'Staff will point the way.'],
        ],
        footer: 'NEED HELP? ASK ANY STAFF MEMBER',
      },
    },
    {
      key: 'department-directory',
      name: 'Department Directory',
      description: 'Two-column wayfinding list of departments and floors.',
      tags: ['directory', 'wayfinding', 'lobby'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'clinical',
        title: 'Department Directory',
        entries: [
          ['Emergency', 'Ground'],
          ['Pharmacy', 'Ground'],
          ['Medical Records', 'Ground'],
          ['Radiology', 'Level 1'],
          ['Pathology Lab', 'Level 1'],
          ['Cardiology', 'Level 2'],
          ['Family Medicine', 'Level 2'],
          ['Pediatrics', 'Level 3'],
          ['Maternity', 'Level 3'],
          ['Orthopedics', 'Level 4'],
          ['Physiotherapy', 'Level 4'],
          ['Oncology Day Unit', 'Level 5'],
        ],
        footer: 'LIFTS AND STAIRS ARE BESIDE THE MAIN LOBBY',
      },
    },

    // ── hours and duty ───────────────────────────────────────────────────────
    {
      key: 'clinic-hours',
      name: 'Clinic Opening Hours',
      description: 'Day-by-day opening hours for the whole practice.',
      tags: ['hours', 'schedule', 'clinic'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'paper',
        title: 'Clinic Hours',
        subtitle: 'RIVERSIDE FAMILY HEALTH',
        colTime: 'DAY',
        colName: 'SERVICE',
        colMeta: 'HOURS',
        rows: [
          ['MON', 'Family Medicine', '08:00 - 18:00'],
          ['TUE', 'Family Medicine', '08:00 - 18:00'],
          ['WED', 'Family Medicine and Labs', '08:00 - 20:00'],
          ['THU', 'Family Medicine', '08:00 - 18:00'],
          ['FRI', 'Family Medicine', '08:00 - 16:00'],
          ['SAT', 'Walk-In Clinic Only', '09:00 - 13:00'],
          ['SUN', 'Emergency Care Only', 'Open 24 hours'],
        ],
        footer: 'CLOSED ON PUBLIC HOLIDAYS',
      },
    },
    {
      key: 'doctor-on-duty',
      name: 'Doctor On Duty',
      description: 'Card naming today’s attending physician, nurse and ward extension.',
      tags: ['staff', 'duty', 'ward'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        title: 'On Duty Today',
        fields: [
          { label: 'ATTENDING PHYSICIAN', value: 'Dr. Amara Okafor' },
          { label: 'DUTY NURSE', value: 'Sister Lena Vogt' },
          { label: 'WARD AND EXTENSION', value: 'Ward 3B, ext. 4412', mono: true },
        ],
        body: 'Rotation changes at 19:00. Ask reception if you need the on-call team.',
      },
    },
    {
      key: 'pharmacy-hours',
      name: 'Pharmacy Hours',
      description: 'Counter, locker and consultation hours with a refill QR code.',
      tags: ['pharmacy', 'hours', 'prescriptions'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'mono',
        title: 'Pharmacy Hours',
        subtitle: 'GROUND FLOOR, ROOM 006',
        colTime: 'DAY',
        colName: 'SERVICE',
        colMeta: 'HOURS',
        rows: [
          ['MON-FRI', 'Prescription Counter', '08:00 - 19:00'],
          ['SAT', 'Prescription Counter', '09:00 - 15:00'],
          ['SUN', 'Emergency Dispensary', '10:00 - 14:00'],
          ['DAILY', 'Pickup Locker', 'Open 24 hours'],
          ['MON-THU', 'Pharmacist Consults', '10:00 - 16:00'],
        ],
        qr: 'https://example.com/repeat-prescription',
        qrLabel: 'Order a refill',
      },
    },
    {
      key: 'visiting-hours',
      name: 'Visiting Hours',
      description: 'Ward visiting windows with the two-visitor rule.',
      tags: ['visiting', 'wards', 'policy'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'paper',
        title: 'Visiting Hours',
        fields: [
          { label: 'GENERAL WARDS', value: '11:00 - 20:00' },
          { label: 'INTENSIVE CARE', value: '15:00 - 17:00' },
          { label: 'MATERNITY UNIT', value: '10:00 - 21:00' },
        ],
        body: 'Two visitors per bed, please. Children under 12 must be with an adult.',
      },
    },

    // ── infection control and conduct ────────────────────────────────────────
    {
      key: 'hand-hygiene',
      name: 'Hand Hygiene Steps',
      description: 'The five-step handwashing routine for sinks and corridors.',
      tags: ['hygiene', 'safety', 'steps'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'clinical',
        title: 'Wash Your Hands',
        steps: [
          ['Wet and lather', 'Warm water first, then soap both hands.'],
          ['Palms and backs', 'Rub palm to palm, then over each hand.'],
          ['Fingers and thumbs', 'Interlace the fingers, twist each thumb.'],
          ['Nails and wrists', 'Scrub fingertips in each palm, then wrists.'],
          ['Rinse and dry', 'Rinse well and dry with a clean towel.'],
        ],
        footer: 'TWENTY SECONDS, EVERY TIME',
      },
    },
    {
      key: 'mask-policy',
      name: 'Mask Policy',
      description: 'Clear notice that masks are required in clinical areas.',
      tags: ['masks', 'policy', 'safety'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'clinical',
        eyebrow: 'INFECTION CONTROL',
        title: 'Masks Required Here',
        titleSize: 0.13,
        body: 'Please wear a mask in all clinical areas. Free masks are at the entrance desk.',
        footer: 'THANK YOU FOR PROTECTING OUR PATIENTS',
      },
    },
    {
      key: 'no-mobile-phones',
      name: 'Take Calls Outside',
      description: 'Phone and recording etiquette notice for consultation areas.',
      tags: ['phones', 'etiquette', 'privacy'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'mono',
        eyebrow: 'CONSULTATION AREA',
        title: 'Please Take Calls Outside',
        titleSize: 0.1,
        body: 'No photos or recording anywhere in the clinic. Thank you for respecting privacy.',
      },
    },
    {
      key: 'quiet-zone',
      name: 'Quiet Zone',
      description: 'Calm dark board for ward corridors and rest areas.',
      tags: ['quiet', 'wards', 'notice'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        eyebrow: 'WARD 4 CORRIDOR',
        title: 'Quiet Zone',
        titleSize: 0.15,
        body: 'Patients are resting. Please keep voices low and phones on silent.',
        footer: 'QUIET HOURS 22:00 - 07:00',
      },
    },
    {
      key: 'smoke-free-site',
      name: 'Smoke-Free Site',
      description: 'Portrait entrance poster covering smoking and vaping.',
      tags: ['smoking', 'policy', 'entrance'],
      recipe: 'announcement',
      orientation: 'portrait',
      spec: {
        palette: 'forest',
        eyebrow: 'ENTIRE CAMPUS',
        title: 'No Smoking',
        titleSize: 0.1,
        body: 'Includes vaping, car parks and all doorways.',
        footer: 'SUPPORT TO QUIT: ASK YOUR NURSE',
      },
    },
    {
      key: 'patient-rights',
      name: 'Your Rights As A Patient',
      description: 'Six-point patient rights notice for waiting areas.',
      tags: ['rights', 'policy', 'patients'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'mono',
        title: 'Your Rights As A Patient',
        steps: [
          ['Respectful care', 'Safe, dignified treatment without discrimination.'],
          ['Clear information', 'Plain-language answers about your diagnosis.'],
          ['Informed consent', 'You may accept or refuse any treatment.'],
          ['Privacy', 'Your records stay confidential at all times.'],
          ['A second opinion', 'Ask us for a referral at any time.'],
          ['To be heard', 'Concerns go to the Patient Liaison Office.'],
        ],
        footer: 'PATIENT LIAISON OFFICE, GROUND FLOOR, ROOM 012',
      },
    },

    // ── emergency and safety ─────────────────────────────────────────────────
    {
      key: 'emergency-numbers',
      name: 'Emergency Numbers',
      description: 'Internal crash, security and crisis extensions at a glance.',
      tags: ['emergency', 'numbers', 'staff'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'crimson',
        title: 'Emergency Numbers',
        entries: [
          ['Ambulance and Fire', '112'],
          ['Cardiac Arrest Team', '2222'],
          ['Rapid Response Nurse', '2233'],
          ['Emergency Department', '4111'],
          ['Hospital Switchboard', '4000'],
          ['Poison Information', '4488'],
          ['Mental Health Crisis Line', '4570'],
          ['Security Desk', '4900'],
          ['Facilities and Spills', '4650'],
          ['Patient Liaison Office', '4012'],
        ],
        footer: 'DIAL 9 FIRST FOR AN OUTSIDE LINE',
      },
    },

    // ── prevention and campaigns ─────────────────────────────────────────────
    {
      key: 'flu-shot-promo',
      name: 'Free Flu Shots',
      description: 'Loud walk-in vaccination promo with a booking QR code.',
      tags: ['vaccination', 'promo', 'flu'],
      recipe: 'promoBurst',
      orientation: 'landscape',
      spec: {
        palette: 'teal',
        eyebrow: 'WALK-IN, NO APPOINTMENT',
        title: 'Free Flu Shots',
        titleSize: 0.17,
        body: 'Every weekday, 09:00 to 16:00, in the Level 1 vaccination room.',
        code: 'ROOM 1B',
        qr: 'https://example.com/flu-clinic',
        qrLabel: 'Book a slot',
        footer: 'BRING YOUR VACCINATION CARD',
      },
    },
    {
      key: 'vaccination-clinics',
      name: 'Vaccination Clinics Today',
      description: 'Timetable of today’s immunisation clinics and rooms.',
      tags: ['vaccination', 'schedule', 'clinic'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'clinical',
        title: 'Vaccination Clinics',
        subtitle: 'TODAY',
        colTime: 'TIME',
        colName: 'CLINIC',
        colMeta: 'ROOM',
        rows: [
          ['09:00', 'Childhood Immunisations', 'Room 12'],
          ['10:30', 'Flu and COVID Boosters', 'Room 14'],
          ['11:30', 'Travel Vaccines', 'Room 15'],
          ['13:00', 'Tetanus and Shingles', 'Room 14'],
          ['14:30', 'HPV Catch-Up Clinic', 'Room 12'],
          ['15:30', 'Pneumococcal Clinic', 'Room 14'],
          ['16:30', 'Walk-In Vaccinations', 'Room 16'],
        ],
        footer: 'ARRIVE FIVE MINUTES BEFORE YOUR SLOT',
      },
    },
    {
      key: 'blood-drive',
      name: 'Blood Donation Drive',
      description: 'Donor bus campaign board with date, hours and booking code.',
      tags: ['blood', 'donation', 'promo'],
      recipe: 'promoBurst',
      orientation: 'landscape',
      spec: {
        palette: 'crimson',
        eyebrow: 'THURSDAY 12 MARCH',
        title: 'Give Blood Today',
        titleSize: 0.16,
        body: 'Donor bus in the main car park, 09:00 to 17:00. Walk-ins welcome.',
        code: 'CODE: DONATE12',
        qr: 'https://example.com/blood-drive',
        qrLabel: 'Book a slot',
      },
    },
    {
      key: 'screening-reminder',
      name: 'Book Your Screening',
      description: 'Photo reminder for bowel, breast and cervical screening.',
      tags: ['screening', 'prevention', 'reminder'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'forest',
        eyebrow: 'AGES 50 TO 74',
        title: 'Book Your Screening',
        titleSize: 0.115,
        anchor: 'bottom',
        body: 'Bowel, breast and cervical screening save lives. Ask reception to book today.',
        scrim: 68,
        qr: 'https://example.com/screening',
        qrLabel: 'Book online',
      },
    },
    {
      key: 'health-tip',
      name: 'Health Tip Of The Day',
      description: 'Rotating pull-quote health tip for waiting rooms.',
      tags: ['wellness', 'tip', 'quote'],
      recipe: 'quoteCard',
      orientation: 'landscape',
      spec: {
        palette: 'paper',
        quote: 'Thirty minutes of walking a day lowers blood pressure more than most people expect.',
        quoteSize: 0.055,
        author: 'HEALTH TIP OF THE DAY',
        footer: 'ASK YOUR GP ABOUT A WALKING PLAN',
      },
    },
    {
      key: 'checkup-packages',
      name: 'Health Check Packages',
      description: 'Three self-pay health check tiers with a booking QR code.',
      tags: ['checkup', 'pricing', 'promo'],
      recipe: 'priceCards',
      orientation: 'landscape',
      spec: {
        palette: 'clinical',
        title: 'Health Check Packages',
        subtitle: 'Book online or at the reception desk',
        cards: [
          { name: 'ESSENTIAL', price: '$89', desc: 'Blood pressure, BMI, cholesterol and blood sugar.' },
          { name: 'COMPLETE', price: '$189', desc: 'Adds full bloods, ECG and a 30-minute doctor review.', featured: true },
          { name: 'EXECUTIVE', price: '$349', desc: 'Adds lung function, ultrasound and a written care plan.' },
        ],
        qr: 'https://example.com/health-checks',
        qrLabel: 'Book a check',
      },
    },
    {
      key: 'telehealth-promo',
      name: 'Telehealth Visits',
      description: 'Split board promoting online video appointments.',
      tags: ['telehealth', 'promo', 'digital'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        eyebrow: 'CARE FROM HOME',
        title: 'See A Doctor Online',
        body: 'Video appointments daily, 08:00 to 20:00. Prescriptions go straight to your pharmacy.',
        qr: 'https://example.com/telehealth',
        qrLabel: 'Book a visit',
      },
    },

    // ── feedback, results and people ─────────────────────────────────────────
    {
      key: 'satisfaction-survey',
      name: 'Patient Satisfaction Survey',
      description: 'Two-minute feedback prompt with a scannable survey code.',
      tags: ['survey', 'feedback', 'qr'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'clinical',
        eyebrow: 'TWO MINUTES, ANONYMOUS',
        title: 'How Did We Do?',
        body: 'Scan the code and rate your visit. Every answer goes to the ward team.',
        cta: 'RATE YOUR VISIT',
        flip: true,
        qr: 'https://example.com/patient-survey',
        qrLabel: 'Start survey',
      },
    },
    {
      key: 'satisfaction-score',
      name: 'Satisfaction Score',
      description: 'Portrait big-number board for the headline recommendation rate.',
      tags: ['feedback', 'stats', 'quality'],
      recipe: 'bigNumber',
      orientation: 'portrait',
      spec: {
        palette: 'teal',
        eyebrow: 'PATIENT FEEDBACK',
        value: '96%',
        valueSize: 0.26,
        label: 'RECOMMEND US',
        body: 'From 1,412 patient surveys this quarter.',
        footer: 'THANK YOU FOR TELLING US',
      },
    },
    {
      key: 'quality-stats',
      name: 'Care Quality Stats',
      description: 'Six quarterly quality and safety figures on one board.',
      tags: ['stats', 'quality', 'report'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        title: 'Our Care This Quarter',
        subtitle: 'QUALITY REPORT',
        tiles: [
          { label: 'SATISFACTION', value: '96%', sub: 'Would recommend us' },
          { label: 'AVERAGE WAIT', value: '14 min', sub: 'Down from 21 minutes', accent: '#22c55e' },
          { label: 'HAND HYGIENE', value: '98%', sub: 'Audit compliance', accent: '#22c55e' },
          { label: 'SAME-DAY SLOTS', value: '1,240', sub: 'Offered this quarter' },
          { label: 'VACCINES GIVEN', value: '3,870', sub: 'Flu and travel clinics' },
          { label: 'INFECTION RATE', value: '0.4%', sub: 'Below national average', accent: '#22c55e' },
        ],
        footer: 'FULL QUALITY REPORT AVAILABLE AT RECEPTION',
      },
    },
    {
      key: 'staff-recognition',
      name: 'Staff Recognition',
      description: 'Photo strip celebrating this month’s nominated staff.',
      tags: ['staff', 'recognition', 'photos'],
      recipe: 'photoStrip',
      orientation: 'landscape',
      spec: {
        palette: 'clinical',
        title: 'Staff Of The Month',
        subtitle: 'Nominated by patients and colleagues',
        frames: 3,
        captions: ['Dr. Priya Raman, Cardiology', 'Marcus Bell, Porter Team', 'Sofia Ionescu, Night Nursing'],
        footer: 'NOMINATE A COLLEAGUE AT THE STAFF PORTAL',
      },
    },

    // ── amenities and money ──────────────────────────────────────────────────
    {
      key: 'self-pay-fees',
      name: 'Self-Pay Fees',
      description: 'Priced list of consultations, tests, vaccines and certificates.',
      tags: ['pricing', 'services', 'fees'],
      recipe: 'menuBoard',
      orientation: 'landscape',
      spec: {
        palette: 'mono',
        title: 'Self-Pay Fees',
        subtitle: 'NO INSURANCE NEEDED',
        columns: 2,
        sections: [
          {
            name: 'CONSULTATIONS',
            items: [
              ['GP Consultation', '$60'],
              ['Nurse Appointment', '$35'],
              ['Repeat Prescription', '$20'],
              ['Travel Health Advice', '$45'],
            ],
          },
          {
            name: 'TESTS AND CHECKS',
            items: [
              ['Blood Pressure Check', '$15'],
              ['Full Blood Count', '$40'],
              ['ECG', '$55'],
            ],
          },
          {
            name: 'VACCINATIONS',
            items: [
              ['Flu Vaccine', '$25'],
              ['Tetanus Booster', '$30'],
              ['Hepatitis B Course', '$120'],
            ],
          },
          {
            name: 'CERTIFICATES',
            items: [
              ['Sick Note', '$15'],
              ['Fitness To Fly Letter', '$40'],
            ],
          },
        ],
        footer: 'CARD PAYMENT AT THE RECEPTION DESK',
      },
    },
    {
      key: 'cafeteria-menu',
      name: 'Cafeteria Menu',
      description: 'Single-column portrait menu for the hospital cafeteria.',
      tags: ['cafeteria', 'menu', 'amenities'],
      recipe: 'menuBoard',
      orientation: 'portrait',
      spec: {
        palette: 'paper',
        title: 'Cafeteria',
        subtitle: 'TODAY',
        columns: 1,
        sections: [
          {
            name: 'HOT MEALS',
            items: [
              ['Grilled Chicken and Rice', '$5.50'],
              ['Vegetable Lasagne', '$5.00'],
              ['Lentil Soup', '$3.20'],
            ],
          },
          {
            name: 'LIGHT BITES',
            items: [
              ['Chicken Salad Bowl', '$4.50'],
              ['Egg and Cress Roll', '$3.40'],
              ['Fruit Cup', '$2.20'],
            ],
          },
          {
            name: 'DRINKS',
            items: [
              ['Filter Coffee', '$1.80'],
              ['Herbal Tea', '$1.60'],
            ],
          },
        ],
        footer: 'LEVEL 1, OPEN 07:00 - 19:00',
      },
    },
    {
      key: 'guest-wifi',
      name: 'Guest Wi-Fi',
      description: 'Network name, password and a join code for visitors.',
      tags: ['wifi', 'visitors', 'amenities'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'mono',
        title: 'Guest Wi-Fi',
        fields: [
          { label: 'NETWORK', value: 'Riverside-Guest' },
          { label: 'PASSWORD', value: 'wellness2025', mono: true },
        ],
        body: 'Free for patients and visitors. Please avoid streaming video in clinical areas.',
        qr: 'https://example.com/guest-wifi',
        qrLabel: 'Join network',
      },
    },
  ],
}
