export default {
  category: 'hospitality',
  name: 'Hospitality',
  description: 'Lobby welcomes, guest info, dining hours and amenity boards for hotels, resorts and inns.',
  icon: '🛎️',
  templates: [
    {
      key: 'lobby-welcome',
      name: 'Lobby Welcome',
      description: 'Full-bleed welcome screen for the main lobby wall.',
      tags: ['welcome', 'lobby'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        display: 'playfair',
        eyebrow: 'The Marlowe Hotel',
        title: 'Welcome Home',
        titleSize: 0.14,
        body: 'Reception is open around the clock. Anything at all, just ask.',
        cta: 'Front desk, ground floor',
        anchor: 'bottom',
        scrim: 66,
      },
    },
    {
      key: 'guest-wifi',
      name: 'Guest WiFi Card',
      description: 'Network name and password with a join-now QR code.',
      tags: ['wifi', 'guest', 'info'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        title: 'Guest WiFi',
        fields: [
          { label: 'Network', value: 'Marlowe-Guest', mono: true },
          { label: 'Password', value: 'staywell2026', mono: true },
          { label: 'Need help', value: 'Dial 0 from your room' },
        ],
        qr: 'https://example.com/wifi',
        qrLabel: 'Scan to join',
      },
    },
    {
      key: 'events-directory',
      name: 'Events and Functions',
      description: 'Todays function rooms and where to find each one.',
      tags: ['events', 'directory'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'charcoal',
        title: 'Today at The Marlowe',
        entries: [
          ['Harrison Wedding Reception', 'Grand Ballroom'],
          ['Northwind Sales Summit', 'Kensington Suite'],
          ['Bar Association Lunch', 'Oak Room'],
          ['Riverside Charity Gala', 'Atrium'],
          ['Product Launch Breakfast', 'Studio 2'],
          ['Coastal Realtors AGM', 'Boardroom A'],
          ['Yoga in the Garden', 'Terrace Lawn'],
          ['Wine Tasting Evening', 'Cellar Bar'],
          ['Graduation Dinner', 'Copperleaf Restaurant'],
          ['Interview Suite', 'Meeting Room 4'],
        ],
        footer: 'Ask any team member for directions',
      },
    },
    {
      key: 'restaurant-hours',
      name: 'Restaurant Hours',
      description: 'Daily service times for every outlet on property.',
      tags: ['dining', 'hours'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'espresso',
        title: 'Dining Today',
        subtitle: 'Service times',
        colTime: 'SERVICE',
        colName: 'VENUE',
        colMeta: 'HOURS',
        rows: [
          ['Breakfast', 'Copperleaf Restaurant', '06:30 - 10:30'],
          ['Lunch', 'Copperleaf Restaurant', '12:00 - 14:30'],
          ['All day', 'Atrium Lounge', '10:00 - 23:00'],
          ['Dinner', 'Copperleaf Restaurant', '17:30 - 22:30'],
          ['Drinks', 'The Long Gallery Bar', '16:00 - 01:00'],
          ['Room service', 'In-room dining', '24 hours'],
        ],
        footer: 'Reservations: dial 4 from any house phone',
      },
    },
    {
      key: 'spa-treatments',
      name: 'Spa Treatments',
      description: 'Three signature spa packages with pricing.',
      tags: ['spa', 'wellness', 'offers'],
      recipe: 'priceCards',
      orientation: 'landscape',
      spec: {
        palette: 'teal',
        display: 'playfair',
        title: 'Aster Spa',
        subtitle: 'Book at reception or dial 6',
        cards: [
          { name: 'Deep Tissue Massage', price: '$120', desc: '60 minutes with warm stone finish' },
          { name: 'Marlowe Signature Ritual', price: '$185', desc: '90 minutes, scrub, wrap and massage', featured: true },
          { name: 'Express Facial', price: '$85', desc: '40 minutes, hydrating and calming' },
        ],
        qr: 'https://example.com/spa',
        qrLabel: 'Book online',
      },
    },
    {
      key: 'room-service-menu',
      name: 'Room Service Menu',
      description: 'Single-column in-room dining menu for lift lobbies.',
      tags: ['menu', 'room service'],
      recipe: 'menuBoard',
      orientation: 'portrait',
      spec: {
        palette: 'espresso',
        title: 'In-Room Dining',
        subtitle: '24 hours',
        columns: 1,
        sections: [
          {
            name: 'To Start',
            items: [
              ['Tomato and Basil Soup', '$9', 'Sourdough croutons'],
              ['Caesar Salad', '$12', 'Add grilled chicken $5'],
            ],
          },
          {
            name: 'Mains',
            items: [
              ['Marlowe Club Sandwich', '$18', 'Skin-on fries'],
              ['Grilled Sirloin', '$34', 'Peppercorn sauce, greens'],
              ['Wild Mushroom Risotto', '$21', 'Parmesan, truffle oil'],
              ['Margherita Pizza', '$16', 'Buffalo mozzarella, basil'],
            ],
          },
          {
            name: 'Sweet',
            items: [
              ['Sticky Toffee Pudding', '$9'],
              ['Seasonal Fruit Plate', '$8'],
            ],
          },
        ],
        qr: 'https://example.com/room-service',
        qrLabel: 'Order now',
        footer: 'Dial 3 to order. Tray charge $5.',
      },
    },
    {
      key: 'checkout-steps',
      name: 'Checkout Steps',
      description: 'Four-step express checkout instructions for guests.',
      tags: ['checkout', 'howto'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        title: 'Express Checkout',
        steps: [
          ['Pack and check the safe', 'Look under the bed and behind the bathroom door'],
          ['Review your folio on the TV', 'Press the Menu button, then Billing'],
          ['Approve the balance', 'Charges settle to the card on file'],
          ['Drop your key in the lobby box', 'Beside the front desk, no queue needed'],
        ],
        footer: 'Checkout by 11:00. Luggage storage is free.',
      },
    },
    {
      key: 'local-attractions',
      name: 'Local Attractions',
      description: 'Nearby sights with walking distance from the door.',
      tags: ['local', 'directory'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'forest',
        title: 'Around the Corner',
        entries: [
          ['Riverside Botanical Gardens', '6 min walk'],
          ['City Art Museum', '10 min walk'],
          ['Old Market Hall', '12 min walk'],
          ['Harbour Boardwalk', '15 min walk'],
          ['Cathedral Quarter', '8 min walk'],
          ['Central Station', '4 min walk'],
          ['Lantern Street Night Market', '11 min walk'],
          ['Observatory Hill Lookout', '20 min walk'],
          ['Grand Theatre', '9 min walk'],
          ['Ferry Terminal', '18 min walk'],
        ],
        footer: 'Printed walking maps at the concierge desk',
      },
    },
    {
      key: 'weather-welcome',
      name: 'Weather and Welcome',
      description: 'Todays forecast tiles for the lobby entrance screen.',
      tags: ['weather', 'welcome'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        title: 'Good Morning',
        subtitle: 'Your day at a glance',
        tiles: [
          { label: 'High', value: '24C', sub: 'Sunny spells', accent: '#f59e0b' },
          { label: 'Low', value: '13C', sub: 'Clear overnight', accent: '#60a5fa' },
          { label: 'Rain', value: '10%', sub: 'Umbrellas at the desk' },
          { label: 'Sunset', value: '19:42', sub: 'Best from the roof terrace', accent: '#fb7185' },
        ],
        footer: 'Terrace bar opens at 16:00',
      },
    },
    {
      key: 'concierge-picks',
      name: 'Concierge Picks',
      description: 'Three staff recommendations with photo frames.',
      tags: ['concierge', 'local'],
      recipe: 'photoStrip',
      orientation: 'landscape',
      spec: {
        palette: 'paper',
        display: 'roboto-slab',
        title: 'Concierge Picks',
        subtitle: 'Chosen by our team this month',
        frames: 3,
        captions: [
          'Sunday jazz at the Old Market Hall',
          'Sunrise kayaking from the boardwalk',
          'Tasting menu at Fern and Fig',
        ],
        qr: 'https://example.com/concierge',
        qrLabel: 'See the full list',
      },
    },
    {
      key: 'shuttle-timetable',
      name: 'Shuttle Timetable',
      description: 'Airport and city shuttle departures from the porte cochere.',
      tags: ['shuttle', 'transport'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'steel',
        title: 'Shuttle Departures',
        subtitle: 'From the main entrance',
        colTime: 'DEPARTS',
        colName: 'ROUTE',
        colMeta: 'JOURNEY',
        rows: [
          ['06:00', 'Airport Terminal 1 and 2', '35 min'],
          ['07:30', 'Airport Terminal 1 and 2', '35 min'],
          ['09:00', 'City Centre Loop', '20 min'],
          ['11:30', 'Airport Terminal 1 and 2', '35 min'],
          ['14:00', 'City Centre Loop', '20 min'],
          ['16:30', 'Airport Terminal 1 and 2', '35 min'],
          ['19:00', 'Harbour and Night Market', '25 min'],
        ],
        footer: 'Complimentary for in-house guests. Please book at reception.',
      },
    },
    {
      key: 'pool-gym-hours',
      name: 'Pool and Gym Hours',
      description: 'Opening times and rules for the leisure floor.',
      tags: ['leisure', 'hours'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        title: 'Leisure Club',
        subtitle: 'Level 2, room key required',
        tiles: [
          { label: 'Pool', value: '06:00', sub: 'Closes 22:00', accent: '#38bdf8' },
          { label: 'Gym', value: '24h', sub: 'Key card access' },
          { label: 'Sauna', value: '12:00', sub: 'Closes 21:00', accent: '#f97316' },
          { label: 'Towels', value: 'Free', sub: 'Take from the shelf' },
        ],
        footer: 'Children under 16 must be supervised at all times',
      },
    },
    {
      key: 'conference-directory',
      name: 'Conference Rooms',
      description: 'Meeting room directory with floor and capacity.',
      tags: ['meetings', 'directory'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        title: 'Meeting and Event Space',
        entries: [
          ['Grand Ballroom', 'Level 1, seats 400'],
          ['Kensington Suite', 'Level 1, seats 120'],
          ['Oak Room', 'Level 2, seats 60'],
          ['Atrium', 'Ground floor, seats 200'],
          ['Studio 1', 'Level 3, seats 30'],
          ['Studio 2', 'Level 3, seats 30'],
          ['Boardroom A', 'Level 4, seats 14'],
          ['Boardroom B', 'Level 4, seats 14'],
          ['Meeting Room 4', 'Level 2, seats 10'],
          ['Terrace Lawn', 'Outdoor, seats 150'],
        ],
        footer: 'Event team on Level 1 or dial 8',
      },
    },
    {
      key: 'breakfast-times',
      name: 'Breakfast Times',
      description: 'Simple statement board for breakfast service hours.',
      tags: ['breakfast', 'hours'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'sand',
        eyebrow: 'Copperleaf Restaurant',
        title: 'Breakfast 6:30 - 10:30',
        titleSize: 0.11,
        body: 'Buffet and cooked to order. Weekends until 11:00.',
        footer: 'Included with most rates. Ask at the desk.',
      },
    },
    {
      key: 'bar-happy-hour',
      name: 'Bar Happy Hour',
      description: 'Loud portrait promo for the daily happy hour.',
      tags: ['bar', 'promo'],
      recipe: 'promoBurst',
      orientation: 'portrait',
      spec: {
        palette: 'crimson',
        eyebrow: 'The Long Gallery Bar',
        title: 'Happy Hour',
        titleSize: 0.15,
        body: 'Half price cocktails, house wine and draught beer, 17:00 to 19:00 daily.',
        code: 'ASK FOR THE LIST',
        footer: 'Level 1, beside the atrium',
      },
    },
    {
      key: 'housekeeping-notice',
      name: 'Housekeeping Notice',
      description: 'Portrait notice for corridor screens during servicing.',
      tags: ['housekeeping', 'notice'],
      recipe: 'announcement',
      orientation: 'portrait',
      spec: {
        palette: 'mono',
        display: 'inter',
        eyebrow: 'Housekeeping',
        title: 'Rooms Serviced 9-3',
        titleSize: 0.1,
        body: 'Hang the door tag if you would rather not be disturbed today.',
        footer: 'Extra towels and pillows: dial 2',
      },
    },
    {
      key: 'guest-review-qr',
      name: 'Guest Review QR',
      description: 'Split screen asking departing guests for a review.',
      tags: ['reviews', 'feedback'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'violet',
        eyebrow: 'Before you go',
        title: 'How Did We Do',
        body: 'Two minutes of your time helps our team enormously. Thank you for staying.',
        cta: 'Scan to leave a review',
        flip: true,
        qr: 'https://example.com/review',
        qrLabel: 'Rate your stay',
      },
    },
    {
      key: 'loyalty-programme',
      name: 'Loyalty Programme',
      description: 'Three membership tiers and their benefits.',
      tags: ['loyalty', 'offers'],
      recipe: 'priceCards',
      orientation: 'landscape',
      spec: {
        palette: 'amber',
        title: 'Marlowe Rewards',
        subtitle: 'Free to join at reception',
        cards: [
          { name: 'Silver', price: 'Free', desc: 'Late checkout and free WiFi upgrade' },
          { name: 'Gold', price: '10 nights', desc: 'Room upgrades and breakfast included', featured: true },
          { name: 'Platinum', price: '30 nights', desc: 'Suite upgrades, lounge access, no fees' },
        ],
        qr: 'https://example.com/rewards',
        qrLabel: 'Join in 60 seconds',
      },
    },
    {
      key: 'late-checkout-offer',
      name: 'Late Checkout Offer',
      description: 'Paid late checkout upsell for lift lobby screens.',
      tags: ['upsell', 'checkout'],
      recipe: 'promoBurst',
      orientation: 'landscape',
      spec: {
        palette: 'rose',
        eyebrow: 'Stay a little longer',
        title: 'Late Checkout $35',
        titleSize: 0.13,
        body: 'Keep your room until 3pm. Subject to availability on the day.',
        code: 'DIAL 0 TO ADD',
        footer: 'Free for Gold and Platinum members',
      },
    },
    {
      key: 'wedding-welcome',
      name: 'Wedding Welcome',
      description: 'Elegant welcome board for a private wedding party.',
      tags: ['wedding', 'events'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'violet',
        display: 'playfair',
        eyebrow: 'The Marlowe welcomes',
        title: 'Sarah and James',
        titleSize: 0.13,
        body: 'Drinks reception on the terrace from 4pm. Dinner in the Grand Ballroom at 6pm.',
        anchor: 'bottom',
        scrim: 70,
      },
    },
    {
      key: 'emergency-exits',
      name: 'Emergency Exits',
      description: 'Clear evacuation steps for corridors and lift lobbies.',
      tags: ['safety', 'emergency'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'clinical',
        display: 'inter',
        title: 'In an Emergency',
        steps: [
          ['Leave the building immediately', 'Do not stop to collect belongings'],
          ['Use the stairs, never the lifts', 'Marked exits at both ends of every corridor'],
          ['Follow the green running man signs', 'Staff in high-visibility vests will guide you'],
          ['Assemble in the car park', 'Wait for the all clear before returning'],
        ],
        footer: 'Emergency line: dial 5 from any house phone',
      },
    },
    {
      key: 'seasonal-greeting',
      name: 'Seasonal Greeting',
      description: 'Portrait festive greeting for lobby and corridor screens.',
      tags: ['seasonal', 'welcome'],
      recipe: 'announcement',
      orientation: 'portrait',
      spec: {
        palette: 'forest',
        display: 'playfair',
        eyebrow: 'From all of us at The Marlowe',
        title: 'Season of Good Cheer',
        titleSize: 0.1,
        body: 'Mulled wine in the lounge from 5pm. Carol singers on Friday evening.',
        footer: 'Festive menus now taking bookings',
      },
    },
    {
      key: 'guest-rating',
      name: 'Guest Rating',
      description: 'Big-number board showing the current guest score.',
      tags: ['reviews', 'trust'],
      recipe: 'bigNumber',
      orientation: 'landscape',
      spec: {
        palette: 'teal',
        eyebrow: 'Guest satisfaction',
        value: '9.4',
        valueSize: 0.34,
        label: 'Out of ten this year',
        body: 'From 2,180 verified reviews. Thank you for staying with us.',
        footer: 'Tell us how we did before you check out',
      },
    },
    {
      key: 'guest-quote',
      name: 'Guest Quote',
      description: 'Pull quote from a recent review for lobby rotation.',
      tags: ['reviews', 'quote'],
      recipe: 'quoteCard',
      orientation: 'landscape',
      spec: {
        palette: 'paper',
        display: 'playfair',
        quote: 'The warmest welcome we have had anywhere. The night team even remembered our order.',
        quoteSize: 0.058,
        author: 'Priya M, stayed in March',
        footer: 'Read more reviews at the concierge desk',
      },
    },
    {
      key: 'cocktail-menu',
      name: 'Bar Cocktail Menu',
      description: 'Two-column signature cocktail and wine list.',
      tags: ['bar', 'menu', 'drinks'],
      recipe: 'menuBoard',
      orientation: 'landscape',
      spec: {
        palette: 'charcoal',
        title: 'The Long Gallery',
        subtitle: 'Open until 1am',
        columns: 2,
        sections: [
          {
            name: 'Signature Cocktails',
            items: [
              ['Marlowe Old Fashioned', '$16', 'Rye, demerara, orange bitters'],
              ['Garden Gimlet', '$14', 'Gin, cucumber, lime cordial'],
              ['Smoked Negroni', '$15', 'Applewood smoke, orange peel'],
              ['Espresso Martini', '$15', 'Local roast, vanilla'],
              ['Harbour Spritz', '$13', 'Aperol, prosecco, soda'],
            ],
          },
          {
            name: 'Wine by the Glass',
            items: [
              ['Sauvignon Blanc', '$11', 'Marlborough, crisp'],
              ['Chardonnay', '$12', 'Lightly oaked'],
              ['Malbec', '$12', 'Mendoza, plush'],
              ['Rioja Reserva', '$13', 'Vanilla and cherry'],
              ['Prosecco', '$10', '125ml'],
            ],
          },
          {
            name: 'Zero Proof',
            items: [
              ['Seedlip and Tonic', '$9'],
              ['Ginger and Lime Cooler', '$7'],
            ],
          },
        ],
        footer: 'Charge to your room, just show your key',
      },
    },
    {
      key: 'rooftop-terrace',
      name: 'Rooftop Terrace',
      description: 'Split promo driving guests to the roof terrace bar.',
      tags: ['bar', 'promo'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'crimson',
        eyebrow: 'Level 12',
        title: 'Sunset on the Roof',
        body: 'Small plates and cocktails with the best view in the city. Open from four.',
        cta: 'Lift to Level 12',
        qr: 'https://example.com/rooftop',
        qrLabel: 'See the menu',
      },
    },
    {
      key: 'breakfast-buffet',
      name: 'Breakfast Buffet Board',
      description: 'What is on the breakfast buffet today, by station.',
      tags: ['breakfast', 'menu'],
      recipe: 'menuBoard',
      orientation: 'landscape',
      spec: {
        palette: 'sand',
        title: 'Breakfast Buffet',
        subtitle: '6:30 - 10:30',
        columns: 2,
        sections: [
          {
            name: 'Hot Station',
            items: [
              ['Scrambled and Poached Eggs'],
              ['Smoked Streaky Bacon'],
              ['Cumberland Sausages'],
              ['Roasted Tomatoes and Mushrooms'],
              ['Buttermilk Pancakes'],
            ],
          },
          {
            name: 'Cold Station',
            items: [
              ['Greek Yoghurt and Granola'],
              ['Seasonal Fruit and Berries'],
              ['Smoked Salmon and Capers'],
              ['Cheese and Charcuterie'],
              ['Fresh Pastries and Sourdough'],
            ],
          },
          {
            name: 'Made to Order',
            items: [
              ['Omelettes', '', 'Chef station by the window'],
              ['Barista Coffee', '', 'Included with breakfast'],
            ],
          },
        ],
        footer: 'Gluten free and dairy free options on request',
      },
    },
    {
      key: 'checkout-time',
      name: 'Checkout Time',
      description: 'Single enormous reminder of the checkout deadline.',
      tags: ['checkout', 'notice'],
      recipe: 'bigNumber',
      orientation: 'landscape',
      spec: {
        palette: 'steel',
        eyebrow: 'Departure day',
        value: '11:00',
        valueSize: 0.26,
        label: 'Checkout time',
        body: 'Late checkout available until 3pm. Free luggage storage in the lobby.',
        footer: 'Ask at reception or dial 0',
      },
    },
  ],
}
