/* Manufacturing pack — shop-floor safety, production performance and plant notices.
 *
 * Written for screens that hang over a line and get read at four metres by
 * someone walking past in ear defenders: short headlines, one idea per board,
 * and numbers big enough to argue about.
 */

export default {
  category: 'manufacturing',
  name: 'Manufacturing',
  description: 'Safety boards, production KPIs, shift information and plant notices for factories and workshops.',
  icon: '🏭',
  templates: [
    // ── safety ───────────────────────────────────────────────────────────────
    {
      key: 'days-since-incident',
      name: 'Days Since Last Incident',
      description: 'The safety counter every plant entrance needs.',
      tags: ['safety', 'counter', 'ehs'],
      recipe: 'bigNumber',
      orientation: 'landscape',
      spec: {
        palette: 'forest',
        eyebrow: 'SAFETY FIRST',
        value: '147',
        label: 'DAYS WITHOUT A LOST-TIME INJURY',
        body: 'Our best run on record is 212 days. Look after each other and we will beat it.',
        footer: 'REPORT EVERY HAZARD - NO JOB IS WORTH AN INJURY',
      },
    },
    {
      key: 'safety-rules',
      name: 'Life-Saving Rules',
      description: 'Six non-negotiable safety rules as numbered steps.',
      tags: ['safety', 'rules', 'ehs'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'crimson',
        title: 'LIFE-SAVING RULES',
        steps: [
          ['Wear your PPE', 'Hard hat, safety glasses and steel toes past the yellow line.'],
          ['Isolate before you touch', 'No energy source stays live while you work on a machine.'],
          ['Guards stay on', 'Never bypass an interlock or run with a guard removed.'],
          ['Mind the traffic', 'Stay in the walkways and make eye contact with every driver.'],
          ['Clip on above two metres', 'Harness and lanyard for all work at height. Every time.'],
          ['Stop the job', 'Anyone can stop unsafe work. Nobody will be questioned for it.'],
        ],
        footer: 'BREAKING A LIFE-SAVING RULE IS THE ONLY WAY TO GET SENT HOME',
      },
    },
    {
      key: 'ppe-required',
      name: 'PPE Required',
      description: 'Portrait door poster listing mandatory protective equipment.',
      tags: ['safety', 'ppe', 'notice'],
      recipe: 'announcement',
      orientation: 'portrait',
      spec: {
        palette: 'amber',
        eyebrow: 'BEYOND THIS POINT',
        title: 'PPE REQUIRED',
        titleSize: 0.1,
        body: 'Safety glasses, hi-vis vest, hearing protection and steel-toe boots. No exceptions, visitors included.',
        footer: 'PPE STORE - BAY 2, NEXT TO THE TIME CLOCKS',
      },
    },
    {
      key: 'lockout-tagout',
      name: 'Lockout / Tagout Steps',
      description: 'The six-step isolation procedure at the machine.',
      tags: ['safety', 'loto', 'procedure'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'amber',
        title: 'LOCKOUT / TAGOUT',
        steps: [
          ['Notify the area', 'Tell the line lead and everyone working on the machine.'],
          ['Shut down properly', 'Use the normal stop sequence, never the emergency stop.'],
          ['Isolate every source', 'Electrical, pneumatic, hydraulic, steam and stored gravity energy.'],
          ['Apply lock and tag', 'Your own padlock and your own name on every isolation point.'],
          ['Release stored energy', 'Bleed lines, block rams and discharge capacitors before you start.'],
          ['Verify zero energy', 'Try to start it. No movement means it is safe.'],
        ],
        footer: 'ONE LOCK PER PERSON - NEVER REMOVE SOMEONE ELSE PADLOCK',
      },
    },
    {
      key: 'emergency-assembly',
      name: 'Emergency Assembly Point',
      description: 'Portrait evacuation notice with the muster point.',
      tags: ['safety', 'emergency', 'notice'],
      recipe: 'announcement',
      orientation: 'portrait',
      spec: {
        palette: 'forest',
        eyebrow: 'IN AN EVACUATION',
        title: 'ASSEMBLY POINT B',
        titleSize: 0.09,
        body: 'Leave by the nearest fire exit. Walk to the car park flagpole. Wait for the roll call.',
        footer: 'DO NOT RE-ENTER UNTIL A FIRE MARSHAL SAYS SO',
      },
    },
    {
      key: 'toolbox-talk',
      name: 'Toolbox Talk Topic',
      description: 'Photo split announcing the daily pre-shift talk.',
      tags: ['safety', 'briefing', 'training'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        eyebrow: 'TODAY TOOLBOX TALK',
        title: 'HAND AND FINGER SAFETY',
        body: 'Five minutes at the line before start-up. Pinch points, glove choice and safe tool handling.',
        cta: 'STARTS 05:55 AT THE BOARD',
        flip: true,
      },
    },
    {
      key: 'near-miss-report',
      name: 'Report a Near Miss',
      description: 'Loud reporting prompt with a scannable form link.',
      tags: ['safety', 'reporting', 'qr'],
      recipe: 'promoBurst',
      orientation: 'landscape',
      spec: {
        palette: 'rose',
        eyebrow: 'SPEAK UP',
        title: 'REPORT A NEAR MISS',
        titleSize: 0.13,
        body: 'Log it in under a minute. No names, no blame, no comeback.',
        qr: 'https://example.com/nearmiss',
        qrLabel: 'Report now',
        footer: 'EVERY REPORT STOPS THE NEXT INJURY',
      },
    },
    {
      key: 'forklift-traffic',
      name: 'Forklift Traffic Warning',
      description: 'High-contrast warning for shared pedestrian routes.',
      tags: ['safety', 'traffic', 'warning'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'amber',
        eyebrow: 'SHARED TRAFFIC ROUTE',
        title: 'FORKLIFTS OPERATING',
        body: 'Stay inside the green walkway. Stop at every crossing. Make eye contact before you step out.',
        footer: 'PEDESTRIAN PRIORITY - DRIVERS GIVE WAY AT ALL CROSSINGS',
      },
    },
    {
      key: 'visitor-induction',
      name: 'Visitor Safety Induction',
      description: 'Reception board sending visitors to the induction video.',
      tags: ['safety', 'visitors', 'induction'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        eyebrow: 'ALL VISITORS AND CONTRACTORS',
        title: 'SAFETY INDUCTION REQUIRED',
        scrim: 66,
        body: 'Report to reception, watch the four-minute induction and collect your badge and safety glasses.',
        qr: 'https://example.com/visitor-induction',
        qrLabel: 'Watch induction',
      },
    },
    {
      key: 'safety-quote',
      name: 'Safety Pledge Quote',
      description: 'Pull quote from the plant manager on stopping unsafe work.',
      tags: ['safety', 'culture', 'quote'],
      recipe: 'quoteCard',
      orientation: 'landscape',
      spec: {
        palette: 'charcoal',
        quote: 'No part, no order and no deadline is worth your hands.',
        quoteSize: 0.062,
        author: 'DANIELLE REYES, PLANT MANAGER',
      },
    },

    // ── production performance ───────────────────────────────────────────────
    {
      key: 'production-kpis',
      name: 'Production KPIs',
      description: 'Six-tile board for OEE, output, scrap and uptime.',
      tags: ['kpi', 'production', 'oee'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'charcoal',
        title: 'PRODUCTION KPIs',
        subtitle: 'SHIFT TO DATE',
        tiles: [
          { label: 'OEE', value: '82.4%', sub: 'Target 85%', accent: '#f59e0b' },
          { label: 'UNITS BUILT', value: '4,180', sub: 'Plan 4,300' },
          { label: 'SCRAP RATE', value: '1.2%', sub: 'Under the 1.5% limit', accent: '#22c55e' },
          { label: 'UPTIME', value: '94.1%', sub: 'Best week since May' },
          { label: 'FIRST PASS YIELD', value: '97.6%', sub: 'Up 0.8 points' },
          { label: 'DOWNTIME', value: '38 min', sub: 'Two stoppages' },
        ],
        footer: 'LIVE FROM THE MES - REFRESHED EVERY 15 MINUTES',
      },
    },
    {
      key: 'target-vs-actual',
      name: 'Target vs Actual',
      description: 'Four tiles comparing shift plan against real output.',
      tags: ['kpi', 'target', 'output'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        title: 'TARGET VS ACTUAL',
        subtitle: 'SHIFT A - TODAY',
        tiles: [
          { label: 'TARGET', value: '4,300', sub: 'Units this shift' },
          { label: 'ACTUAL', value: '4,180', sub: '120 behind plan', accent: '#f59e0b' },
          { label: 'PACE', value: '523/hr', sub: 'Need 540 per hour' },
          { label: 'HOURS LEFT', value: '2.5', sub: 'Still recoverable', accent: '#22c55e' },
        ],
        footer: 'PULL BACK 17 UNITS AN HOUR AND WE FINISH ON PLAN',
      },
    },
    {
      key: 'oee-live',
      name: 'Live OEE',
      description: 'Portrait single-number board for one line OEE.',
      tags: ['kpi', 'oee', 'line'],
      recipe: 'bigNumber',
      orientation: 'portrait',
      spec: {
        palette: 'teal',
        eyebrow: 'LINE 4 ASSEMBLY',
        value: '82.4%',
        valueSize: 0.24,
        label: 'OEE THIS SHIFT',
        body: 'Availability 94 percent. Performance 91 percent. Quality 96 percent. Plant target is 85 percent.',
        footer: 'UPDATED EVERY FIVE MINUTES',
      },
    },
    {
      key: 'line-status',
      name: 'Line Status Board',
      description: 'Twelve production lines with their current running state.',
      tags: ['production', 'status', 'lines'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'steel',
        title: 'LINE STATUS BOARD',
        entries: [
          ['Line 1 - Press Shop', 'RUNNING'],
          ['Line 2 - Weld Cell', 'RUNNING'],
          ['Line 3 - Paint', 'CHANGEOVER'],
          ['Line 4 - Assembly', 'RUNNING'],
          ['Line 5 - Sub-assembly', 'RUNNING'],
          ['Line 6 - Injection', 'DOWN'],
          ['Line 7 - Extrusion', 'RUNNING'],
          ['Line 8 - Packaging', 'RUNNING'],
          ['CNC Cell A', 'RUNNING'],
          ['CNC Cell B', 'PM DUE'],
          ['Test Rig 1', 'RUNNING'],
          ['Test Rig 2', 'IDLE'],
        ],
        footer: 'RED LINES GET THE MAINTENANCE TEAM FIRST',
      },
    },
    {
      key: 'downtime-reasons',
      name: 'Top Downtime Reasons',
      description: 'Lost minutes by cause over the last seven days.',
      tags: ['downtime', 'analysis', 'production'],
      recipe: 'menuBoard',
      orientation: 'landscape',
      spec: {
        palette: 'steel',
        title: 'TOP DOWNTIME REASONS',
        subtitle: 'LAST 7 DAYS',
        columns: 2,
        sections: [
          {
            name: 'MECHANICAL',
            items: [
              ['Conveyor jam', '212 min'],
              ['Robot fault - Cell 4', '96 min'],
              ['Gripper change', '54 min'],
            ],
          },
          {
            name: 'PROCESS',
            items: [
              ['Tool change', '148 min'],
              ['Colour changeover', '110 min'],
              ['Waiting on material', '87 min'],
            ],
          },
          {
            name: 'QUALITY',
            items: [
              ['Gauge recalibration', '63 min'],
              ['Rework loop', '41 min'],
            ],
          },
          {
            name: 'OTHER',
            items: [
              ['Late start-up', '35 min'],
              ['Air pressure loss', '28 min'],
            ],
          },
        ],
        footer: 'THE TOP THREE ARE 60 PERCENT OF ALL LOST MINUTES',
      },
    },
    {
      key: 'quality-alert',
      name: 'Quality Alert',
      description: 'Urgent batch hold notice with a link to the alert detail.',
      tags: ['quality', 'alert', 'hold'],
      recipe: 'promoBurst',
      orientation: 'landscape',
      spec: {
        palette: 'crimson',
        eyebrow: 'QUALITY ALERT - LEVEL 2',
        title: 'HOLD BATCH 4471',
        titleSize: 0.15,
        body: 'Bearing housings are quarantined. Do not ship. Route all stock to the red cage.',
        code: 'BATCH 4471',
        qr: 'https://example.com/quality/alert-4471',
        qrLabel: 'Alert detail',
      },
    },

    // ── shift and operations ─────────────────────────────────────────────────
    {
      key: 'shift-schedule',
      name: 'Shift Schedule',
      description: 'Crew start times and team leads for the week.',
      tags: ['shift', 'schedule', 'crew'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        title: 'SHIFT SCHEDULE',
        subtitle: 'WEEK 33',
        colTime: 'START',
        colName: 'CREW',
        colMeta: 'TEAM LEAD',
        rows: [
          ['06:00', 'A Crew - Assembly', 'D. Okafor'],
          ['06:00', 'B Crew - Machining', 'L. Ferreira'],
          ['08:00', 'Warehouse - Days', 'A. Kaur'],
          ['14:00', 'C Crew - Assembly', 'M. Novak'],
          ['14:00', 'D Crew - Machining', 'S. Bennett'],
          ['22:00', 'E Crew - Nights', 'R. Haddad'],
          ['22:00', 'Maintenance - Nights', 'T. Whitfield'],
        ],
        footer: 'SWAPS MUST BE AGREED WITH THE SHIFT MANAGER BY THURSDAY',
      },
    },
    {
      key: 'shift-handover',
      name: 'Shift Handover Checklist',
      description: 'Six things every outgoing lead hands over.',
      tags: ['shift', 'handover', 'checklist'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'teal',
        title: 'SHIFT HANDOVER',
        steps: [
          ['Walk the line together', 'Outgoing and incoming leads, five minutes, machine by machine.'],
          ['Hand over the numbers', 'Output, scrap and OEE against plan for the shift.'],
          ['Flag open faults', 'Anything degraded, on a temporary fix or waiting on parts.'],
          ['Confirm quality holds', 'Batches on hold, open concessions and any customer complaint.'],
          ['Check materials', 'Stock at the line, incoming deliveries and short kits.'],
          ['Sign the log', 'Both leads sign. No signature means no handover.'],
        ],
        footer: 'HANDOVER LOG LIVES ON THE LINE 4 TERMINAL',
      },
    },
    {
      key: 'maintenance-window',
      name: 'Planned Maintenance Window',
      description: 'Card giving the line, window and work order for a shutdown.',
      tags: ['maintenance', 'planned', 'notice'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        title: 'PLANNED MAINTENANCE',
        fields: [
          { label: 'LINE', value: 'Line 6 - Injection' },
          { label: 'WINDOW', value: 'Sat 23 Aug 22:00-04:00' },
          { label: 'WORK ORDER', value: 'WO-88214', mono: true },
        ],
        qr: 'https://example.com/maintenance/wo-88214',
        qrLabel: 'Work order',
        body: 'Line 6 will be fully isolated. Plan your material moves around the window.',
      },
    },
    {
      key: 'training-calendar',
      name: 'Training This Week',
      description: 'Course times and rooms for the week ahead.',
      tags: ['training', 'schedule', 'compliance'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'violet',
        title: 'TRAINING THIS WEEK',
        subtitle: 'BOOK WITH YOUR LEAD',
        colTime: 'WHEN',
        colName: 'COURSE',
        colMeta: 'ROOM',
        rows: [
          ['Mon 07:00', 'Forklift refresher', 'Training Room 1'],
          ['Mon 13:00', 'Lockout / tagout', 'Training Room 2'],
          ['Tue 07:00', 'Manual handling', 'Training Room 1'],
          ['Wed 09:00', 'Working at height', 'Yard bay 4'],
          ['Wed 14:00', 'Gauge and SPC basics', 'Metrology lab'],
          ['Thu 07:00', 'Fire marshal refresher', 'Training Room 2'],
          ['Fri 10:00', 'New starter induction', 'Reception'],
        ],
      },
    },
    {
      key: 'training-compliance',
      name: 'Training Compliance',
      description: 'Four tiles showing certification coverage across the plant.',
      tags: ['training', 'compliance', 'kpi'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'violet',
        title: 'TRAINING COMPLIANCE',
        subtitle: 'PLANT WIDE',
        tiles: [
          { label: 'FORKLIFT LICENCES', value: '100%', sub: '42 of 42 current', accent: '#22c55e' },
          { label: 'LOTO AUTHORISED', value: '96%', sub: 'Three refreshers due', accent: '#f59e0b' },
          { label: 'FIRST AID TRAINED', value: '18', sub: 'Responders on site' },
          { label: 'INDUCTIONS DONE', value: '11', sub: 'New starters this month' },
        ],
        footer: 'EXPIRED CERTIFICATE MEANS OFF THE TRUCK - BOOK EARLY',
      },
    },
    {
      key: 'emergency-contacts',
      name: 'Emergency Contacts',
      description: 'Internal extensions for fire, first aid and duty engineers.',
      tags: ['emergency', 'contacts', 'directory'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'mono',
        title: 'EMERGENCY CONTACTS',
        entries: [
          ['Fire and ambulance', '112'],
          ['Plant emergency line', '2222'],
          ['Security gatehouse', '2100'],
          ['First aid - Assembly', '2145'],
          ['First aid - Machining', '2147'],
          ['Maintenance callout', '2300'],
          ['Duty electrical engineer', '2312'],
          ['Spill response team', '2360'],
          ['Quality hold desk', '2280'],
          ['Occupational health', '2410'],
          ['Shift manager', '2050'],
          ['Environmental officer', '2375'],
        ],
        footer: 'DIAL 2222 FIRST - STATE YOUR LOCATION, THEN THE EMERGENCY',
      },
    },

    // ── plant life ───────────────────────────────────────────────────────────
    {
      key: 'plant-announcement',
      name: 'Plant Announcement',
      description: 'Site-wide notice with a scannable detail page.',
      tags: ['announcement', 'plant', 'notice'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        eyebrow: 'PLANT NOTICE',
        title: 'SHUTDOWN WEEK 34',
        titleSize: 0.11,
        body: 'Full site shutdown Monday 18 to Friday 22 August. Only approved maintenance crews on site.',
        qr: 'https://example.com/shutdown-plan',
        qrLabel: 'Shutdown plan',
      },
    },
    {
      key: 'waste-recycling',
      name: 'Waste and Recycling Guide',
      description: 'Which bin takes what, by colour, at the segregation point.',
      tags: ['waste', 'recycling', 'environment'],
      recipe: 'menuBoard',
      orientation: 'landscape',
      spec: {
        palette: 'forest',
        title: 'WASTE AND RECYCLING',
        subtitle: 'SEGREGATE AT SOURCE',
        columns: 2,
        sections: [
          {
            name: 'RECYCLE',
            items: [
              ['Cardboard and paper', 'BLUE'],
              ['Clean plastic film', 'YELLOW'],
              ['Steel and aluminium offcuts', 'GREY'],
            ],
          },
          {
            name: 'HAZARDOUS',
            items: [
              ['Oily rags and filters', 'RED'],
              ['Used coolant and oil', 'RED'],
              ['Batteries and lamps', 'RED'],
            ],
          },
          {
            name: 'GENERAL',
            items: [
              ['Canteen waste', 'BLACK'],
              ['Worn-out PPE', 'BLACK'],
              ['Floor sweepings', 'BLACK'],
            ],
          },
        ],
        footer: 'A CONTAMINATED SKIP COSTS US - WHEN IN DOUBT, ASK YOUR LEAD',
      },
    },
    {
      key: 'hygiene-notice',
      name: 'Hygiene at the Line',
      description: 'Five hygiene rules for entry into clean production areas.',
      tags: ['hygiene', 'rules', 'quality'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'clinical',
        title: 'HYGIENE AT THE LINE',
        steps: [
          ['Wash before you enter', 'Twenty seconds with soap and water at the entry sinks.'],
          ['Hair and beard nets on', 'Full cover before you cross the blue line.'],
          ['No jewellery or watches', 'Plain wedding band only. Lockers are in the changing room.'],
          ['Report illness', 'Stomach upset or a skin infection keeps you off the line.'],
          ['Sanitise on return', 'Every break, every washroom visit, every glove change.'],
        ],
        footer: 'SPOT CHECKS RUN DAILY ON ALL PRODUCTION ENTRANCES',
      },
    },
    {
      key: 'operator-recognition',
      name: 'Operators of the Month',
      description: 'Photo strip recognising three crew-nominated operators.',
      tags: ['recognition', 'people', 'culture'],
      recipe: 'photoStrip',
      orientation: 'landscape',
      spec: {
        palette: 'sand',
        title: 'OPERATORS OF THE MONTH',
        subtitle: 'Nominated by their own crews',
        frames: 3,
        captions: [
          'Priya Raman - Weld Cell',
          'Marco Silva - Press Shop',
          'Nadia Osei - Packaging',
        ],
        footer: 'NOMINATE A COLLEAGUE AT THE SHIFT OFFICE',
      },
    },
    {
      key: 'improvement-rewards',
      name: 'Improvement Idea Rewards',
      description: 'Three payout tiers for the continuous improvement scheme.',
      tags: ['kaizen', 'rewards', 'engagement'],
      recipe: 'priceCards',
      orientation: 'landscape',
      spec: {
        palette: 'espresso',
        title: 'IMPROVEMENT IDEA REWARDS',
        subtitle: 'Every approved idea pays out',
        cards: [
          { name: 'IDEA LOGGED', price: '$25', desc: 'Any idea accepted onto the improvement board' },
          { name: 'IMPLEMENTED', price: '$150', desc: 'Built, running and proven on the line', featured: true },
          { name: 'BIG WIN', price: '$1,000', desc: 'Saves over 100 hours or 10,000 dollars a year' },
        ],
        qr: 'https://example.com/improvement-ideas',
        qrLabel: 'Submit an idea',
      },
    },
    {
      key: 'canteen-menu',
      name: 'Canteen Menu',
      description: 'Portrait single-column menu for the plant canteen.',
      tags: ['canteen', 'menu', 'welfare'],
      recipe: 'menuBoard',
      orientation: 'portrait',
      spec: {
        palette: 'paper',
        title: 'CANTEEN TODAY',
        subtitle: 'MON 18 AUG',
        sections: [
          {
            name: 'HOT PLATE',
            items: [
              ['Beef stew and mash', '4.20'],
              ['Chicken curry and rice', '4.20'],
              ['Vegetable lasagne', '3.90'],
            ],
          },
          {
            name: 'GRAB AND GO',
            items: [
              ['Ham and cheese baguette', '2.80'],
              ['Chicken salad box', '3.40'],
              ['Fruit pot', '1.20'],
            ],
          },
          {
            name: 'DRINKS',
            items: [
              ['Filter coffee', '0.80'],
              ['Cold drinks', '1.10'],
            ],
          },
        ],
      },
    },
  ],
}
