export default {
  category: 'offices',
  name: 'Offices',
  description: 'Lobby welcomes, meeting room schedules, KPIs and staff notices for offices and workplaces.',
  icon: '🏢',
  templates: [
    {
      key: 'lobby-welcome',
      name: 'Lobby Welcome',
      description: 'Reception greeting with sign-in prompt and QR.',
      tags: ['lobby', 'welcome', 'reception'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        display: 'bebas',
        eyebrow: 'Northline Group',
        title: 'Welcome to Northline',
        titleSize: 0.12,
        body: 'Please sign in at reception. Your host will be notified automatically.',
        cta: 'Sign in on the tablet',
        qr: 'https://example.com/visitor-signin',
        qrLabel: 'Pre-register',
      },
    },
    {
      key: 'visitor-checkin',
      name: 'Visitor Sign-In Steps',
      description: 'Four numbered steps for the reception check-in flow.',
      tags: ['visitor', 'reception', 'steps'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        display: 'oswald',
        title: 'Visitor Sign-In',
        steps: [
          ['Tap the screen', 'Select Visitor on the reception tablet'],
          ['Enter your details', 'Name, company and who you are here to see'],
          ['Take a photo', 'The tablet prints your badge automatically'],
          ['Wait in the lounge', 'Your host is notified and will collect you'],
        ],
        footer: 'Questions? Reception is open 07:30 to 18:00',
      },
    },
    {
      key: 'reception-hours',
      name: 'Reception Desk Info',
      description: 'Opening hours, deliveries desk and contact extension.',
      tags: ['reception', 'hours', 'info'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'mono',
        display: 'inter',
        title: 'Reception',
        fields: [
          { label: 'Staffed hours', value: 'Mon to Fri, 07:30 - 18:00' },
          { label: 'Deliveries', value: 'Loading bay, Level B1' },
          { label: 'Front desk', value: 'Ext. 2200', mono: true },
        ],
        body: 'Out of hours, use the intercom by the main doors.',
        qr: 'https://example.com/contact-reception',
        qrLabel: 'Contact us',
      },
    },
    {
      key: 'meeting-rooms',
      name: 'Meeting Room Schedule',
      description: 'Today’s room bookings by time, meeting and room.',
      tags: ['meetings', 'rooms', 'schedule'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        display: 'bebas',
        title: 'Meeting Rooms Today',
        subtitle: 'Level 3 booking board',
        colTime: 'TIME',
        colName: 'MEETING',
        colMeta: 'ROOM',
        rows: [
          ['09:00', 'Product standup', 'Aspen'],
          ['10:00', 'Client review: Halden', 'Boardroom'],
          ['11:30', 'Design critique', 'Birch'],
          ['13:00', 'Finance monthly close', 'Cedar'],
          ['14:30', 'Engineering planning', 'Aspen'],
          ['16:00', 'New starter induction', 'Birch'],
        ],
        footer: 'Book a room in Outlook or at any door panel',
      },
    },
    {
      key: 'today-at-a-glance',
      name: 'Today At A Glance',
      description: 'Everything happening in the building today.',
      tags: ['today', 'agenda', 'lobby'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'charcoal',
        display: 'oswald',
        title: 'Today At A Glance',
        subtitle: 'Thursday, Level 1 to Level 6',
        colTime: 'TIME',
        colName: 'WHAT',
        colMeta: 'WHERE',
        rows: [
          ['08:00', 'Breakfast service', 'Cafeteria'],
          ['09:30', 'Fire alarm test', 'All floors'],
          ['12:00', 'Lunch and learn: AI tools', 'Auditorium'],
          ['15:00', 'Blood donation drive', 'Level 2 Atrium'],
          ['16:30', 'Yoga class', 'Wellness Room'],
          ['17:30', 'Leavers drinks: Priya S.', 'Roof Terrace'],
        ],
      },
    },
    {
      key: 'company-kpis',
      name: 'Company KPI Board',
      description: 'Four headline business metrics for the month.',
      tags: ['kpi', 'dashboard', 'metrics'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        display: 'bebas',
        title: 'Company Scorecard',
        subtitle: 'Month to date, updated hourly',
        tiles: [
          { label: 'Revenue', value: '$4.2M', sub: 'Up 12% on last month', accent: '#3b82f6' },
          { label: 'New Clients', value: '38', sub: 'Target 30', accent: '#22c55e' },
          { label: 'NPS', value: '61', sub: 'Up 4 points' },
          { label: 'On-Time Delivery', value: '94%', sub: 'Target 95%', accent: '#f59e0b' },
        ],
        footer: 'Full dashboard on the intranet',
      },
    },
    {
      key: 'quarterly-goals',
      name: 'Quarterly Goals',
      description: 'Progress against the three company goals this quarter.',
      tags: ['goals', 'okr', 'quarter'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'forest',
        display: 'inter',
        title: 'Q3 Goals',
        subtitle: 'Where we stand with six weeks to go',
        tiles: [
          { label: 'Grow ARR', value: '78%', sub: '$3.9M of $5M', accent: '#22c55e' },
          { label: 'Retention', value: '96%', sub: 'Goal 95%' },
          { label: 'Ship Mobile v2', value: '3 of 4', sub: 'Milestones complete' },
          { label: 'Hire Engineers', value: '9/12', sub: 'Three offers out' },
        ],
      },
    },
    {
      key: 'sales-leaderboard',
      name: 'Sales Leaderboard',
      description: 'Top ten closers this month with booked revenue.',
      tags: ['sales', 'leaderboard'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'crimson',
        display: 'bebas',
        title: 'Sales Leaderboard',
        entries: [
          ['1. Marcus Bell', '$412K'],
          ['2. Priya Raman', '$388K'],
          ['3. Dan Okoro', '$355K'],
          ['4. Sofia Marchetti', '$341K'],
          ['5. Tom Whitaker', '$298K'],
          ['6. Aisha Karim', '$276K'],
          ['7. Lena Novak', '$254K'],
          ['8. Chris Dunne', '$231K'],
          ['9. Yuki Tanaka', '$219K'],
          ['10. Grace Adeyemi', '$205K'],
        ],
        footer: 'Booked revenue, month to date',
      },
    },
    {
      key: 'revenue-milestone',
      name: 'Revenue Milestone',
      description: 'One enormous figure celebrating a company record.',
      tags: ['revenue', 'milestone'],
      recipe: 'bigNumber',
      orientation: 'landscape',
      spec: {
        palette: 'amber',
        display: 'bebas',
        eyebrow: 'Company Record',
        value: '$50M',
        valueSize: 0.3,
        label: 'Annual recurring revenue',
        body: 'Passed this morning, three months ahead of plan. Thank you, everyone.',
        footer: 'Celebration drinks Friday, 17:00, Roof Terrace',
      },
    },
    {
      key: 'employee-of-month',
      name: 'Employee Of The Month',
      description: 'Portrait spotlight poster for the monthly award.',
      tags: ['people', 'award', 'recognition'],
      recipe: 'heroOverlay',
      orientation: 'portrait',
      spec: {
        palette: 'violet',
        display: 'playfair',
        eyebrow: 'Employee Of The Month',
        title: 'Priya Raman',
        titleSize: 0.11,
        body: 'Client Services. Rebuilt our onboarding playbook and cut setup time in half.',
        cta: 'Nominated by eleven colleagues',
        anchor: 'bottom',
        scrim: 70,
        qr: 'https://example.com/nominate',
        qrLabel: 'Nominate someone',
      },
    },
    {
      key: 'birthdays-anniversaries',
      name: 'Birthdays And Anniversaries',
      description: 'This month’s celebrations across the business.',
      tags: ['people', 'birthdays', 'culture'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'rose',
        display: 'inter',
        title: 'Celebrating This Month',
        entries: [
          ['Dan Okoro', 'Birthday, 3rd'],
          ['Hannah Croft', 'Birthday, 8th'],
          ['Ibrahim Sayed', 'Birthday, 14th'],
          ['Mei Chen', 'Birthday, 21st'],
          ['Rob Feeney', 'Birthday, 27th'],
          ['Sofia Marchetti', '5 years'],
          ['Tom Whitaker', '5 years'],
          ['Grace Adeyemi', '10 years'],
          ['Alan Pryce', '15 years'],
          ['Jo Bennett', '20 years'],
        ],
        footer: 'Cake in the Level 3 kitchen every last Friday',
      },
    },
    {
      key: 'new-starters',
      name: 'New Starters',
      description: 'Three photo frames introducing this week’s joiners.',
      tags: ['people', 'onboarding'],
      recipe: 'photoStrip',
      orientation: 'landscape',
      spec: {
        palette: 'teal',
        display: 'oswald',
        title: 'Meet Our New Starters',
        subtitle: 'Joining us this week',
        frames: 3,
        captions: [
          'Elena Moss, Product Designer, Level 4',
          'Sam Osei, Backend Engineer, Level 5',
          'Nadia Haddad, Finance Analyst, Level 2',
        ],
        footer: 'Buddy sign-up is open on the intranet',
      },
    },
    {
      key: 'town-hall',
      name: 'Town Hall Announcement',
      description: 'All-hands meeting notice with a joining QR.',
      tags: ['announcement', 'town hall'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        display: 'bebas',
        eyebrow: 'All Hands',
        title: 'Town Hall Thursday',
        titleSize: 0.14,
        body: '15:00 in the Auditorium, or join on Teams. Q3 results and the year ahead.',
        qr: 'https://example.com/town-hall',
        qrLabel: 'Join online',
        footer: 'Submit a question in advance',
      },
    },
    {
      key: 'health-safety',
      name: 'Health And Safety Notice',
      description: 'Standing safety reminder for shared floors.',
      tags: ['safety', 'notice'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'amber',
        display: 'oswald',
        eyebrow: 'Health And Safety',
        title: 'Keep Fire Doors Clear',
        titleSize: 0.11,
        body: 'Never prop open a fire door. Report blocked exits to Facilities on ext. 2410.',
        footer: 'First aiders are listed by every lift lobby',
      },
    },
    {
      key: 'fire-evacuation',
      name: 'Fire Evacuation Steps',
      description: 'Portrait emergency procedure with five clear steps.',
      tags: ['safety', 'emergency', 'steps'],
      recipe: 'stepList',
      orientation: 'portrait',
      spec: {
        palette: 'crimson',
        display: 'bebas',
        title: 'If The Alarm Sounds',
        steps: [
          ['Stop what you are doing', 'Leave belongings and laptops at your desk'],
          ['Use the nearest stairs', 'Never use the lifts during an evacuation'],
          ['Follow the green signs', 'Marshals in hi-vis will direct you down'],
          ['Assemble in Cooper Square', 'Across the road, by the fountain'],
          ['Wait for the all clear', 'Only a fire marshal can send you back in'],
        ],
        footer: 'Alarm tested every Wednesday at 09:30',
      },
    },
    {
      key: 'wifi-guest',
      name: 'Guest Wifi Access',
      description: 'Network name, daily password and a join QR.',
      tags: ['wifi', 'guest', 'info'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'clinical',
        display: 'inter',
        title: 'Guest Wifi',
        fields: [
          { label: 'Network', value: 'Northline-Guest', mono: true },
          { label: 'Password', value: 'welcome2024', mono: true },
          { label: 'Valid', value: '24 hours from first login' },
        ],
        body: 'Scan to connect without typing the password.',
        qr: 'https://example.com/guest-wifi',
        qrLabel: 'Connect',
      },
    },
    {
      key: 'cafeteria-menu',
      name: 'Cafeteria Menu',
      description: 'Two-column staff restaurant menu with prices.',
      tags: ['cafeteria', 'menu', 'food'],
      recipe: 'menuBoard',
      orientation: 'landscape',
      spec: {
        palette: 'espresso',
        display: 'roboto-slab',
        title: 'Staff Restaurant',
        subtitle: 'Level 6, served 11:30 to 14:30',
        columns: 2,
        sections: [
          {
            name: 'Hot Counter',
            items: [
              ['Chicken katsu curry', '5.20', 'Sticky rice, pickled slaw'],
              ['Beef chilli bowl', '5.50', 'Sour cream, corn chips'],
              ['Mushroom stroganoff', '4.80', 'Vegan, wild rice'],
              ['Fish pie', '5.40', 'Buttered greens'],
              ['Soup of the day', '2.90', 'With sourdough'],
            ],
          },
          {
            name: 'Deli And Grab-Go',
            items: [
              ['Build your own salad', '4.50', 'Six toppings'],
              ['Halloumi wrap', '4.20'],
              ['Club sandwich', '3.90'],
              ['Overnight oats', '2.40'],
              ['Fruit pot', '1.80'],
            ],
          },
        ],
        qr: 'https://example.com/menu',
        qrLabel: 'Full week',
        footer: 'Allergen information available at the till',
      },
    },
    {
      key: 'coffee-bar',
      name: 'Coffee Bar Prices',
      description: 'Portrait single-column drinks list for the barista bar.',
      tags: ['coffee', 'menu', 'cafe'],
      recipe: 'menuBoard',
      orientation: 'portrait',
      spec: {
        palette: 'paper',
        display: 'playfair',
        title: 'The Atrium Bar',
        subtitle: 'Staff price, keep cup 30c off',
        columns: 1,
        sections: [
          {
            items: [
              ['Filter coffee', '1.60'],
              ['Americano', '1.90'],
              ['Flat white', '2.40'],
              ['Cappuccino', '2.40'],
              ['Oat latte', '2.60'],
              ['Matcha latte', '2.90'],
              ['Loose leaf tea', '1.70'],
              ['Hot chocolate', '2.50'],
            ],
          },
        ],
        footer: 'Open 07:30 to 16:00, Level 1',
      },
    },
    {
      key: 'shuttle-times',
      name: 'Shuttle Bus Times',
      description: 'Departure board for the station shuttle.',
      tags: ['shuttle', 'transport', 'commute'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'steel',
        display: 'oswald',
        title: 'Station Shuttle',
        subtitle: 'Departs from the North Gate canopy',
        colTime: 'DEPARTS',
        colName: 'SERVICE',
        colMeta: 'STOP',
        rows: [
          ['07:20', 'Central Station', 'North Gate'],
          ['07:50', 'Central Station', 'North Gate'],
          ['08:20', 'Central Station and Riverside', 'North Gate'],
          ['16:45', 'Central Station', 'South Lobby'],
          ['17:15', 'Central Station', 'South Lobby'],
          ['17:45', 'Central Station and Riverside', 'South Lobby'],
        ],
        footer: 'Live running times on the commuter app',
      },
    },
    {
      key: 'parking-permits',
      name: 'Parking Permit Options',
      description: 'Three permit tiers with monthly prices.',
      tags: ['parking', 'permits', 'commute'],
      recipe: 'priceCards',
      orientation: 'landscape',
      spec: {
        palette: 'sand',
        display: 'bebas',
        title: 'Staff Parking',
        subtitle: 'Monthly permits, deducted from payroll',
        cards: [
          { name: 'Day Pass', price: '$4', desc: 'Pay per day, Level B2 only' },
          { name: 'Standard', price: '$45', desc: 'Reserved bay, B1 and B2', featured: true },
          { name: 'EV Charging', price: '$60', desc: 'Bay with 22kW charger' },
        ],
        qr: 'https://example.com/parking',
        qrLabel: 'Apply',
        footer: 'Cycle storage and lockers are free at B1',
      },
    },
    {
      key: 'department-directory',
      name: 'Department Directory',
      description: 'Which team sits on which floor.',
      tags: ['directory', 'wayfinding'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'mono',
        display: 'inter',
        title: 'Building Directory',
        entries: [
          ['Reception and Visitors', 'Level 1'],
          ['Finance', 'Level 2'],
          ['People and Talent', 'Level 2'],
          ['Marketing', 'Level 3'],
          ['Sales', 'Level 3'],
          ['Product and Design', 'Level 4'],
          ['Engineering', 'Level 5'],
          ['IT Service Desk', 'Level 5'],
          ['Legal', 'Level 6'],
          ['Staff Restaurant', 'Level 6'],
          ['Wellness Room', 'Level 4'],
          ['Post and Deliveries', 'Level B1'],
        ],
        footer: 'Lift lobbies on every floor have a plan of the building',
      },
    },
    {
      key: 'project-milestone',
      name: 'Project Milestone',
      description: 'Countdown figure for a major launch.',
      tags: ['project', 'milestone', 'countdown'],
      recipe: 'bigNumber',
      orientation: 'landscape',
      spec: {
        palette: 'teal',
        display: 'bebas',
        eyebrow: 'Project Horizon',
        value: '14',
        valueSize: 0.36,
        label: 'Days until go-live',
        body: 'Migration freeze starts Monday. Raise blockers with your team lead today.',
        footer: 'Launch readiness review, Friday 14:00, Boardroom',
      },
    },
    {
      key: 'training-schedule',
      name: 'Training Schedule',
      description: 'This week’s learning sessions and rooms.',
      tags: ['training', 'learning', 'schedule'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        display: 'inter',
        title: 'Learning This Week',
        subtitle: 'Free to attend, book on the intranet',
        colTime: 'WHEN',
        colName: 'SESSION',
        colMeta: 'ROOM',
        rows: [
          ['Mon 10:00', 'Excel: pivot tables', 'Birch'],
          ['Tue 12:00', 'Presenting with confidence', 'Auditorium'],
          ['Wed 09:30', 'Data protection refresher', 'Online'],
          ['Wed 15:00', 'First aid at work', 'Cedar'],
          ['Thu 12:00', 'Lunch and learn: AI tools', 'Auditorium'],
          ['Fri 11:00', 'New manager essentials', 'Aspen'],
        ],
        footer: 'Ask your manager about study leave',
      },
    },
    {
      key: 'holiday-closure',
      name: 'Holiday Closure Notice',
      description: 'Portrait poster for the seasonal shutdown dates.',
      tags: ['holiday', 'closure', 'notice'],
      recipe: 'announcement',
      orientation: 'portrait',
      spec: {
        palette: 'espresso',
        display: 'playfair',
        eyebrow: 'Office Closure',
        title: 'Closed 24 Dec to 2 Jan',
        titleSize: 0.09,
        body: 'The building reopens Monday 5 January at 07:30. Security and IT on-call cover continues.',
        footer: 'Thank you for a brilliant year',
      },
    },
    {
      key: 'motivational-quote',
      name: 'Motivational Quote',
      description: 'Pull quote for corridors and break-out areas.',
      tags: ['quote', 'culture'],
      recipe: 'quoteCard',
      orientation: 'landscape',
      spec: {
        palette: 'charcoal',
        display: 'playfair',
        quote: 'Great things are done by a series of small things brought together.',
        quoteSize: 0.058,
        author: 'Vincent van Gogh',
        footer: 'Northline Group',
      },
    },
    {
      key: 'it-maintenance',
      name: 'IT Maintenance Window',
      description: 'Planned downtime notice with systems affected.',
      tags: ['it', 'maintenance', 'notice'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'steel',
        display: 'mono',
        title: 'Planned IT Maintenance',
        fields: [
          { label: 'When', value: 'Saturday 02:00 - 06:00' },
          { label: 'Affected', value: 'VPN, file shares, expenses portal' },
          { label: 'Service desk', value: 'Ext. 2500', mono: true },
        ],
        body: 'Save your work before you leave Friday. Email and Teams stay online.',
      },
    },
    {
      key: 'referral-bonus',
      name: 'Referral Bonus',
      description: 'Loud promo for the employee referral scheme.',
      tags: ['hiring', 'referral', 'promo'],
      recipe: 'promoBurst',
      orientation: 'landscape',
      spec: {
        palette: 'violet',
        display: 'bebas',
        eyebrow: 'We Are Hiring',
        title: 'Refer A Friend, Get $2,000',
        titleSize: 0.13,
        body: 'Paid when they pass probation. Eleven open roles across Engineering and Sales.',
        code: 'REFER2K',
        qr: 'https://example.com/careers',
        qrLabel: 'Open roles',
      },
    },
    {
      key: 'wellness-week',
      name: 'Wellness Week',
      description: 'Full-bleed poster for the staff wellbeing programme.',
      tags: ['wellbeing', 'events'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'forest',
        display: 'oswald',
        eyebrow: 'Next Week',
        title: 'Wellness Week',
        titleSize: 0.13,
        body: 'Free health checks, lunchtime walks, yoga and a talk on sleep. All welcome.',
        cta: 'Sign up at reception',
        anchor: 'bottom',
        scrim: 66,
      },
    },
  ],
}
