export default {
  category: 'personalize',
  name: 'Personalize',
  description: 'Everyday screens any business needs: greetings, notices, opening hours, wifi, hiring and celebrations.',
  icon: '✨',
  templates: [
    {
      key: 'happy-birthday',
      name: 'Happy Birthday',
      description: 'Warm birthday message with room for a name and a time.',
      tags: ['celebration', 'birthday', 'team'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'rose',
        display: 'pacifico',
        eyebrow: 'TODAY WE CELEBRATE',
        title: 'Happy Birthday, Sarah',
        titleSize: 0.11,
        body: 'Cake in the break room at 3pm. Come and say hello.',
        footer: 'From everyone on the team',
      },
    },
    {
      key: 'congratulations',
      name: 'Congratulations',
      description: 'Photo-backed congratulations board for a milestone or a win.',
      tags: ['celebration', 'team', 'milestone'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'violet',
        eyebrow: 'A BIG MOMENT',
        title: 'Congratulations, Ana',
        titleSize: 0.115,
        body: 'Ten years with us this week, and still the first one in.',
        cta: 'Drinks at four',
        anchor: 'bottom',
        scrim: 68,
      },
    },
    {
      key: 'welcome-guest',
      name: 'Welcome Guest',
      description: 'Named welcome for a visiting client, group or delegation.',
      tags: ['welcome', 'reception', 'visitors'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        eyebrow: 'WELCOME',
        title: 'Welcome, Nordvik Group',
        titleSize: 0.088,
        body: 'Your session is in the Cedar Room on level two. Coffee is ready.',
        cta: 'Ask at reception',
        flip: true,
      },
    },
    {
      key: 'we-are-open',
      name: 'We Are Open',
      description: 'Bold open sign for the door or window screen.',
      tags: ['open', 'hours', 'door'],
      recipe: 'announcement',
      orientation: 'portrait',
      spec: {
        palette: 'forest',
        eyebrow: 'COME ON IN',
        title: 'We Are Open',
        titleSize: 0.115,
        body: 'Walk-ins welcome all day. Last orders at 9pm.',
        footer: 'Open seven days a week',
      },
    },
    {
      key: 'we-are-closed',
      name: 'Closed Today',
      description: 'Closed notice with return time and an online option.',
      tags: ['closed', 'notice', 'hours'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'crimson',
        eyebrow: 'SORRY WE MISSED YOU',
        title: 'Closed Today',
        titleSize: 0.14,
        body: 'Back tomorrow at 8am. You can still order online any time.',
        qr: 'https://example.com/order',
        qrLabel: 'Order online',
        footer: 'Thanks for stopping by',
      },
    },
    {
      key: 'be-right-back',
      name: 'Be Right Back',
      description: 'Short-break screen with the minutes shown huge.',
      tags: ['break', 'notice', 'counter'],
      recipe: 'bigNumber',
      orientation: 'landscape',
      spec: {
        palette: 'amber',
        eyebrow: 'BACK SHORTLY',
        value: '15',
        label: 'MINUTES',
        body: 'We are on a short break. Please take a seat, we will not be long.',
        footer: 'Thank you for waiting',
      },
    },
    {
      key: 'wifi-password',
      name: 'Wi-Fi Password Card',
      description: 'Guest network name, password and a scan-to-join code.',
      tags: ['wifi', 'guest', 'info'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'charcoal',
        title: 'Guest Wi-Fi',
        fields: [
          { label: 'NETWORK', value: 'Copper-Guest' },
          { label: 'PASSWORD', value: 'sunrise-88', mono: true },
        ],
        qr: 'https://example.com/wifi',
        qrLabel: 'Scan to join',
        body: 'Free for customers. No sign-in page, just connect.',
      },
    },
    {
      key: 'follow-us',
      name: 'Follow Us',
      description: 'Social handles with a scan code to follow instantly.',
      tags: ['social', 'marketing', 'qr'],
      recipe: 'infoCard',
      orientation: 'portrait',
      spec: {
        palette: 'indigo',
        title: 'Follow Us',
        fields: [
          { label: 'INSTAGRAM', value: '@coppercollective' },
          { label: 'FACEBOOK', value: '/coppercollective' },
        ],
        qr: 'https://example.com/social',
        qrLabel: 'Scan to follow',
        body: 'News, offers and behind the scenes, first.',
      },
    },
    {
      key: 'thank-you',
      name: 'Thank You',
      description: 'Elegant thank-you card for customers or a departing colleague.',
      tags: ['thanks', 'customers'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'paper',
        display: 'playfair',
        eyebrow: 'FROM ALL OF US',
        title: 'Thank You',
        titleSize: 0.16,
        body: 'Your support this year has meant everything to our small team.',
        footer: 'See you again soon',
      },
    },
    {
      key: 'now-hiring',
      name: 'Now Hiring',
      description: 'Recruitment split with role details and a scan-to-apply code.',
      tags: ['hiring', 'jobs', 'recruit'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'teal',
        eyebrow: 'JOIN THE TEAM',
        title: 'Now Hiring',
        titleSize: 0.12,
        body: 'Full and part-time roles. Training provided, weekend availability preferred.',
        cta: 'Apply in two minutes',
        qr: 'https://example.com/careers',
        qrLabel: 'Scan to apply',
      },
    },
    {
      key: 'quote-of-the-day',
      name: 'Quote of the Day',
      description: 'Rotating pull quote to set the tone for the day.',
      tags: ['quote', 'motivation'],
      recipe: 'quoteCard',
      orientation: 'landscape',
      spec: {
        palette: 'espresso',
        quote: 'Do the small things with great care, every single day.',
        quoteSize: 0.062,
        author: 'Our house rule',
        footer: 'Quote of the day',
      },
    },
    {
      key: 'countdown-to-event',
      name: 'Countdown to Event',
      description: 'Days-to-go counter building up to a launch or open day.',
      tags: ['countdown', 'event', 'promo'],
      recipe: 'bigNumber',
      orientation: 'portrait',
      spec: {
        palette: 'ocean',
        eyebrow: 'SUMMER SHOWCASE',
        value: '12',
        label: 'DAYS TO GO',
        body: 'Doors open Friday 20 June at 6pm. Everyone welcome.',
        footer: 'Free tickets at the front desk',
      },
    },
    {
      key: 'visitor-info-card',
      name: 'Visitor Info Card',
      description: 'Key visitor details: reception, parking and access code.',
      tags: ['info', 'visitors', 'reception'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'steel',
        title: 'Visitor Information',
        fields: [
          { label: 'RECEPTION', value: 'Level 1, main entrance' },
          { label: 'PARKING', value: 'Bays 40 to 65' },
          { label: 'DOOR CODE', value: '4417#', mono: true },
        ],
        body: 'Please sign in on arrival and wear your badge.',
      },
    },
    {
      key: 'meeting-in-progress',
      name: 'Meeting in Progress',
      description: 'Do-not-disturb door screen with the room free-again time.',
      tags: ['meeting', 'office', 'door'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        eyebrow: 'CEDAR ROOM',
        title: 'Meeting in Progress',
        titleSize: 0.105,
        body: 'Please do not disturb. This room is free again at 11:30.',
        footer: 'Book rooms at reception',
      },
    },
    {
      key: 'wait-to-be-seated',
      name: 'Please Wait to Be Seated',
      description: 'Entrance screen asking guests to wait for a host.',
      tags: ['welcome', 'seating', 'door'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'espresso',
        eyebrow: 'WELCOME IN',
        title: 'Please Wait Here',
        titleSize: 0.12,
        body: 'A member of the team will seat you shortly.',
        footer: 'Thank you for your patience',
      },
    },
    {
      key: 'sanitise-hands',
      name: 'Sanitise Your Hands',
      description: 'Three-step hand hygiene reminder for entrances.',
      tags: ['hygiene', 'safety', 'steps'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'clinical',
        title: 'Sanitise Your Hands',
        steps: [
          ['Take one pump', 'A single press covers both hands.'],
          ['Rub for 20 seconds', 'Palms, backs, between fingers and thumbs.'],
          ['Let it air dry', 'Do not wipe it off on clothing.'],
        ],
        footer: 'Stations at every entrance',
      },
    },
    {
      key: 'new-opening-hours',
      name: 'New Opening Hours',
      description: 'Full week of updated hours in a clean row layout.',
      tags: ['hours', 'notice', 'week'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'mono',
        title: 'New Opening Hours',
        subtitle: 'From Monday 1 September',
        colTime: 'DAY',
        colName: 'OPEN',
        colMeta: 'KITCHEN',
        rows: [
          ['Mon', '8:00 - 17:00', 'Until 16:00'],
          ['Tue', '8:00 - 17:00', 'Until 16:00'],
          ['Wed', '8:00 - 21:00', 'Until 20:00'],
          ['Thu', '8:00 - 21:00', 'Until 20:00'],
          ['Fri', '8:00 - 23:00', 'Until 22:00'],
          ['Sat', '9:00 - 23:00', 'Until 22:00'],
          ['Sun', '10:00 - 16:00', 'Until 15:00'],
        ],
        footer: 'Bank holidays 10:00 - 16:00',
      },
    },
    {
      key: 'holiday-greeting',
      name: 'Holiday Greeting',
      description: 'Festive greeting with the closure dates underneath.',
      tags: ['holiday', 'greeting', 'closed'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'crimson',
        display: 'playfair',
        eyebrow: 'FROM OUR TEAM TO YOURS',
        title: 'Season\'s Greetings',
        titleSize: 0.11,
        body: 'Closed 25 and 26 December. Back at 9am on the 27th.',
        anchor: 'bottom',
        scrim: 70,
      },
    },
    {
      key: 'festive-greeting',
      name: 'Festive Greeting',
      description: 'Generic seasonal greeting that suits any celebration.',
      tags: ['greeting', 'festive', 'season'],
      recipe: 'announcement',
      orientation: 'portrait',
      spec: {
        palette: 'indigo',
        eyebrow: 'WISHING YOU',
        title: 'Light and Joy',
        titleSize: 0.115,
        body: 'However you celebrate this season, we hope it is a happy one.',
        footer: 'From all of us here',
      },
    },
    {
      key: 'team-photo-board',
      name: 'Team Photo Board',
      description: 'Three framed team portraits with names and roles.',
      tags: ['team', 'photos', 'people'],
      recipe: 'photoStrip',
      orientation: 'landscape',
      spec: {
        palette: 'sand',
        title: 'Meet the Team',
        subtitle: 'Here to help, every day',
        frames: 3,
        captions: ['Ana Ruiz, Front of House', 'Marcus Bell, Kitchen Lead', 'Priya Shah, Duty Manager'],
        footer: 'Say hello any time',
      },
    },
    {
      key: 'notice-board',
      name: 'Notice Board',
      description: 'Who is in today and where to find them.',
      tags: ['notice', 'team', 'directory'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'steel',
        title: 'Who Is In Today',
        entries: [
          ['Ana Ruiz', 'Front desk'],
          ['Marcus Bell', 'Kitchen'],
          ['Priya Shah', 'Floor, all day'],
          ['Tom Okafor', 'Stockroom'],
          ['Lena Fischer', 'Office, level 2'],
          ['Jo Hartley', 'Deliveries'],
          ['Sam Deveraux', 'Training room'],
          ['Nadia Karim', 'Off site until 2pm'],
          ['Chris Mwangi', 'Late shift from 4pm'],
          ['Ellie Grant', 'On leave'],
        ],
        footer: 'Updated each morning at 8am',
      },
    },
    {
      key: 'event-schedule',
      name: 'Event Schedule',
      description: 'Running order for the day with times and rooms.',
      tags: ['event', 'schedule', 'agenda'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'violet',
        title: 'Today at the Hall',
        subtitle: 'Doors open at 9:00',
        colTime: 'TIME',
        colName: 'SESSION',
        colMeta: 'ROOM',
        rows: [
          ['09:30', 'Welcome and coffee', 'Foyer'],
          ['10:00', 'Opening talk', 'Main Hall'],
          ['11:15', 'Hands-on workshop', 'Studio 2'],
          ['12:30', 'Lunch', 'Terrace'],
          ['14:00', 'Panel discussion', 'Main Hall'],
          ['15:30', 'Open questions', 'Studio 1'],
          ['16:30', 'Close and drinks', 'Foyer'],
        ],
        footer: 'Programme may change on the day',
      },
    },
    {
      key: 'headline-poster',
      name: 'Headline Poster',
      description: 'One photo, one headline. The simplest poster in the pack.',
      tags: ['poster', 'headline', 'photo'],
      recipe: 'heroOverlay',
      orientation: 'portrait',
      spec: {
        palette: 'charcoal',
        eyebrow: 'THIS WEEK',
        title: 'Late Nights Are Back',
        titleSize: 0.105,
        body: 'Open until 11pm, Thursday through Saturday.',
        cta: 'No booking needed',
        anchor: 'bottom',
        scrim: 72,
      },
    },
    {
      key: 'staff-of-the-month',
      name: 'Staff of the Month',
      description: 'Recognition board for a named team member.',
      tags: ['team', 'recognition'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'amber',
        eyebrow: 'STAFF OF THE MONTH',
        title: 'Marcus Bell',
        titleSize: 0.12,
        body: 'Nominated by six colleagues for covering half-term almost single-handed.',
        cta: 'Coffee on us all month',
      },
    },
    {
      key: 'year-in-numbers',
      name: 'Year in Numbers',
      description: 'Four proud figures from the past twelve months.',
      tags: ['stats', 'milestone', 'thanks'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        title: 'Our Year in Numbers',
        subtitle: 'Thank you for being part of it',
        tiles: [
          { label: 'Customers served', value: '48,200' },
          { label: 'New members', value: '1,340' },
          { label: 'Team members', value: '27' },
          { label: 'Years open', value: '12', accent: '#f6c453' },
        ],
        footer: 'Here is to the next one',
      },
    },
    {
      key: 'gift-cards',
      name: 'Gift Cards',
      description: 'Three gift card values with the popular one highlighted.',
      tags: ['gift', 'offer', 'retail'],
      recipe: 'priceCards',
      orientation: 'landscape',
      spec: {
        palette: 'paper',
        title: 'Gift Cards',
        subtitle: 'Any amount, never expires',
        cards: [
          { name: 'Thank You', price: '$25', desc: 'A small gesture' },
          { name: 'Celebrate', price: '$50', desc: 'Our most popular', featured: true },
          { name: 'The Big One', price: '$100', desc: 'For the serious occasion' },
        ],
        qr: 'https://example.com/gift-cards',
        qrLabel: 'Buy online',
        footer: 'Ask at the counter',
      },
    },
    {
      key: 'opening-soon',
      name: 'Opening Soon',
      description: 'Loud announcement for a new site or a reopening.',
      tags: ['opening', 'promo', 'news'],
      recipe: 'promoBurst',
      orientation: 'landscape',
      spec: {
        palette: 'teal',
        eyebrow: 'COMING SOON',
        title: 'Opening 14 March',
        titleSize: 0.13,
        body: 'New home, same team. Two doors down at number 46.',
        qr: 'https://example.com/opening',
        qrLabel: 'See the plans',
        footer: 'Follow along for the countdown',
      },
    },
    {
      key: 'tell-us-how-we-did',
      name: 'Tell Us How We Did',
      description: 'Feedback prompt with a scan code for the review form.',
      tags: ['feedback', 'reviews', 'qr'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'forest',
        eyebrow: 'THIRTY SECONDS, THAT IS ALL',
        title: 'Tell Us How We Did',
        titleSize: 0.105,
        body: 'Good or bad, we read every single one.',
        qr: 'https://example.com/feedback',
        qrLabel: 'Leave feedback',
        footer: 'Thank you for helping us improve',
      },
    },
  ],
}
