/* Retail template pack.
 *
 * Shop-floor signage: sale bursts, product spotlights, wayfinding, loyalty and
 * service info. Copy is written for a mid-size high street department store so
 * an operator can swap names and prices without rewriting the layout.
 */

export default {
  category: 'retail',
  name: 'Retail',
  description: 'Sale promos, product spotlights, store hours and wayfinding for shops and retail parks.',
  icon: '🛍️',
  templates: [
    // ── sale and promo ───────────────────────────────────────────────────────
    {
      key: 'big-sale',
      name: 'Big Sale Event',
      description: 'Loud storewide sale burst with an online discount code.',
      tags: ['sale', 'promo'],
      recipe: 'promoBurst',
      orientation: 'landscape',
      spec: {
        palette: 'crimson',
        display: 'bebas',
        eyebrow: 'THREE DAYS ONLY',
        title: 'UP TO 70% OFF',
        titleSize: 0.15,
        body: 'Every department, every floor. Online too, with the code below.',
        code: 'BIG70',
        footer: 'Sale ends Sunday at 18:00',
      },
    },
    {
      key: 'percent-off-burst',
      name: 'Percentage Off Burst',
      description: 'Portrait poster built around one enormous discount figure.',
      tags: ['sale', 'poster', 'discount'],
      recipe: 'bigNumber',
      orientation: 'portrait',
      spec: {
        palette: 'rose',
        display: 'bebas',
        eyebrow: 'THIS WEEKEND ONLY',
        value: '50%',
        valueSize: 0.34,
        label: 'OFF EVERY DRESS',
        body: 'Selected rails on Level 1. No code needed at the till.',
        footer: 'Saturday and Sunday only',
      },
    },
    {
      key: 'bogo',
      name: 'Buy One Get One Free',
      description: 'Mix and match BOGO offer across basics and essentials.',
      tags: ['offer', 'promo'],
      recipe: 'promoBurst',
      orientation: 'landscape',
      spec: {
        palette: 'amber',
        display: 'bebas',
        eyebrow: 'MIX AND MATCH',
        title: 'BUY ONE GET ONE FREE',
        titleSize: 0.13,
        body: 'All tees, socks and basics. Cheapest item comes off at the till.',
        footer: 'Level 1 and Level 2 - while stocks last',
      },
    },
    {
      key: 'three-for-two',
      name: 'Three For Two Bundle',
      description: 'Bundle offer burst for beauty, candles and gifting.',
      tags: ['bundle', 'offer'],
      recipe: 'promoBurst',
      orientation: 'landscape',
      spec: {
        palette: 'violet',
        display: 'oswald',
        eyebrow: 'BUNDLE AND SAVE',
        title: 'THREE FOR TWO',
        titleSize: 0.17,
        body: 'Across beauty, candles and gifting. Lowest priced item is free.',
        footer: 'Ground floor Beauty Hall',
      },
    },
    {
      key: 'flash-sale',
      name: 'Flash Sale Countdown',
      description: 'Hours remaining on a same-day extra discount.',
      tags: ['flash', 'countdown', 'sale'],
      recipe: 'bigNumber',
      orientation: 'landscape',
      spec: {
        palette: 'amber',
        display: 'bebas',
        eyebrow: 'FLASH SALE',
        value: '3:00',
        valueSize: 0.28,
        label: 'HOURS REMAINING',
        body: 'Extra 20 percent off already reduced lines. Ends at 17:00 today.',
        footer: 'Ask a colleague for your discount slip',
      },
    },
    {
      key: 'clearance',
      name: 'Clearance Rack',
      description: 'Final reductions notice for the clearance area.',
      tags: ['clearance', 'sale'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'steel',
        display: 'bebas',
        eyebrow: 'FINAL REDUCTIONS',
        title: 'CLEARANCE',
        titleSize: 0.16,
        body: 'Last chance sizes and colours. When they are gone, they are gone.',
        footer: 'No returns or exchanges on clearance stock',
      },
    },

    // ── seasonal campaigns ───────────────────────────────────────────────────
    {
      key: 'black-friday',
      name: 'Black Friday Poster',
      description: 'Portrait announcement for the Black Friday weekend.',
      tags: ['seasonal', 'sale', 'poster'],
      recipe: 'announcement',
      orientation: 'portrait',
      spec: {
        palette: 'charcoal',
        display: 'bebas',
        eyebrow: 'DOORS OPEN 6AM FRIDAY',
        title: 'BLACK FRIDAY',
        titleSize: 0.12,
        body: 'Up to 60 percent off across every department. Four days only.',
        footer: 'Friday 27 to Monday 30 November',
      },
    },
    {
      key: 'back-to-school',
      name: 'Back To School',
      description: 'Photo campaign for uniform, shoes and stationery.',
      tags: ['seasonal', 'campaign'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'forest',
        display: 'oswald',
        eyebrow: 'BACK TO SCHOOL',
        title: 'Kitted Out By September',
        titleSize: 0.11,
        body: 'Uniform, shoes, bags and stationery. Two for 15 pounds on polo shirts.',
        cta: 'Level 2 - Kidswear',
        anchor: 'bottom',
        scrim: 68,
      },
    },
    {
      key: 'holiday-shop',
      name: 'Holiday Shop Open',
      description: 'Festive gifting campaign with a free wrapping hook.',
      tags: ['seasonal', 'gifts'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'crimson',
        display: 'playfair',
        eyebrow: 'THE HOLIDAY SHOP',
        title: 'Everything Wrapped Up',
        titleSize: 0.12,
        body: 'Gifts, decorations and food to share. Free gift wrapping over 40 pounds.',
        cta: 'Level 1 - Gift Hall',
        scrim: 66,
      },
    },
    {
      key: 'summer-edit',
      name: 'Summer Edit',
      description: 'Seasonal split hero for the summer clothing campaign.',
      tags: ['seasonal', 'campaign', 'fashion'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'sand',
        display: 'playfair',
        eyebrow: 'THE SUMMER EDIT',
        title: 'Made For Long Evenings',
        titleSize: 0.11,
        body: 'Linen, sandals and swim. New pieces landing every Thursday.',
        cta: 'Level 1 - Womenswear',
      },
    },

    // ── product and merchandising ────────────────────────────────────────────
    {
      key: 'new-arrivals',
      name: 'New Arrivals Strip',
      description: 'Three photo frames for this week new stock.',
      tags: ['new', 'photos'],
      recipe: 'photoStrip',
      orientation: 'landscape',
      spec: {
        palette: 'mono',
        display: 'inter',
        title: 'New In This Week',
        subtitle: 'Fresh drops across every floor',
        frames: 3,
        captions: ['Linen Shirting - Level 1', 'Everyday Denim - Level 1', 'Canvas Totes - Level 2'],
        qr: 'https://example.com/new-in',
        qrLabel: 'Shop new in',
      },
    },
    {
      key: 'product-spotlight',
      name: 'Product Spotlight',
      description: 'Single hero product with specification and shelf location.',
      tags: ['product', 'spotlight'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        display: 'inter',
        eyebrow: 'JUST LANDED',
        title: 'Aurora Wireless Headphones',
        titleSize: 0.1,
        body: 'Forty hour battery, active noise cancelling and a two year warranty.',
        cta: '179 pounds - Aisle 4',
        qr: 'https://example.com/aurora-headphones',
        qrLabel: 'Read reviews',
      },
    },
    {
      key: 'price-compare',
      name: 'Price Comparison Cards',
      description: 'Three models side by side with the middle one featured.',
      tags: ['compare', 'prices'],
      recipe: 'priceCards',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        display: 'oswald',
        title: 'Compare The Range',
        subtitle: 'Aster kettles - Level 3, Electronics',
        cards: [
          { name: 'Aster 1.7L', price: '29', desc: 'Rapid boil. One year warranty.' },
          { name: 'Aster Pro', price: '49', desc: 'Temperature control. Three year warranty.', featured: true },
          { name: 'Aster Studio', price: '79', desc: 'Brushed steel. Five year warranty.' },
        ],
        footer: 'All prices in pounds. Price match on request.',
      },
    },
    {
      key: 'weekly-deals',
      name: 'Deals Of The Week',
      description: 'Two column priced list of this week reduced lines.',
      tags: ['deals', 'prices'],
      recipe: 'menuBoard',
      orientation: 'landscape',
      spec: {
        palette: 'forest',
        display: 'oswald',
        title: 'Deals Of The Week',
        subtitle: 'Monday 16 to Sunday 22 March - prices in pounds',
        columns: 2,
        sections: [
          {
            name: 'Home and Kitchen',
            items: [
              ['Stoneware Mug Set of 4', '12', 'Was 20'],
              ['Cast Iron Casserole 4L', '45', 'Was 75'],
              ['Cotton Bath Towel', '8', 'Two for 14'],
              ['LED Desk Lamp', '18', 'Was 26'],
            ],
          },
          {
            name: 'Wardrobe',
            items: [
              ['Merino Crew Jumper', '29', 'Was 45'],
              ['Everyday Denim Jeans', '25', 'Any two for 40'],
              ['Leather Trainers', '39', 'Was 60'],
              ['Wool Blend Scarf', '12', 'Was 18'],
            ],
          },
        ],
        footer: 'Offers apply in store and online',
      },
    },
    {
      key: 'staff-pick',
      name: 'Staff Pick',
      description: 'Pull quote recommendation from a named colleague.',
      tags: ['product', 'quote'],
      recipe: 'quoteCard',
      orientation: 'landscape',
      spec: {
        palette: 'paper',
        display: 'playfair',
        quote: 'The linen shirt I reach for every single day of summer.',
        quoteSize: 0.06,
        author: 'Priya - Womenswear, Level 1',
        footer: 'Staff picks change every fortnight',
      },
    },
    {
      key: 'size-guide',
      name: 'Size Guide',
      description: 'Womenswear and menswear sizing chart in two columns.',
      tags: ['sizing', 'help'],
      recipe: 'menuBoard',
      orientation: 'landscape',
      spec: {
        palette: 'mono',
        display: 'inter',
        title: 'Size Guide',
        subtitle: 'All measurements in centimetres',
        columns: 2,
        sections: [
          {
            name: 'Womenswear',
            items: [
              ['XS', 'UK 6', 'Bust 80 / Waist 62'],
              ['S', 'UK 8', 'Bust 84 / Waist 66'],
              ['M', 'UK 12', 'Bust 92 / Waist 74'],
              ['L', 'UK 16', 'Bust 100 / Waist 82'],
              ['XL', 'UK 20', 'Bust 112 / Waist 94'],
            ],
          },
          {
            name: 'Menswear',
            items: [
              ['S', '36 in', 'Chest 91 / Waist 78'],
              ['M', '40 in', 'Chest 101 / Waist 86'],
              ['L', '44 in', 'Chest 112 / Waist 96'],
              ['XL', '48 in', 'Chest 122 / Waist 106'],
              ['XXL', '52 in', 'Chest 132 / Waist 116'],
            ],
          },
        ],
        footer: 'Fitting rooms are on every floor',
      },
    },

    // ── service, membership and info ─────────────────────────────────────────
    {
      key: 'store-hours',
      name: 'Store Hours',
      description: 'Opening times for every day with collection notes.',
      tags: ['hours', 'info'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'charcoal',
        display: 'oswald',
        title: 'Store Hours',
        subtitle: 'Northgate Retail Park',
        colTime: 'DAY',
        colName: 'OPEN',
        colMeta: 'NOTES',
        rows: [
          ['Monday', '09:00 - 18:00', 'Collections until 17:30'],
          ['Tuesday', '09:00 - 18:00', 'Collections until 17:30'],
          ['Wednesday', '09:00 - 18:00', 'Beauty bar open late'],
          ['Thursday', '09:00 - 20:00', 'Late night shopping'],
          ['Friday', '09:00 - 20:00', 'Late night shopping'],
          ['Saturday', '08:30 - 20:00', 'Busiest 11:00 to 15:00'],
          ['Sunday', '10:00 - 16:00', 'Browsing from 09:30'],
        ],
        footer: 'Bank holidays 10:00 to 16:00',
      },
    },
    {
      key: 'store-directory',
      name: 'Store Directory',
      description: 'Floor guide listing departments and services.',
      tags: ['wayfinding', 'directory'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        display: 'inter',
        title: 'Store Directory',
        entries: [
          ['Beauty Hall', 'Ground'],
          ['Customer Service', 'Ground'],
          ['Click and Collect', 'Ground'],
          ['Womenswear', 'Level 1'],
          ['Menswear', 'Level 1'],
          ['Gift Wrapping', 'Level 1'],
          ['Footwear', 'Level 2'],
          ['Kidswear', 'Level 2'],
          ['Sportswear', 'Level 2'],
          ['Baby Change', 'Level 2'],
          ['Home and Kitchen', 'Level 3'],
          ['Electronics', 'Level 3'],
          ['The Rooftop Cafe', 'Level 3'],
          ['Car Park Lifts', 'Ground'],
        ],
        footer: 'Lifts and step free access at the Bridge Street entrance',
      },
    },
    {
      key: 'click-and-collect',
      name: 'Click And Collect Steps',
      description: 'Four numbered steps from order to collection.',
      tags: ['collect', 'howto', 'service'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        display: 'inter',
        title: 'Click And Collect',
        steps: [
          ['Order online', 'Choose collect in store at the checkout.'],
          ['Wait for the text', 'Most orders are ready within two hours.'],
          ['Come to the desk', 'Ground floor, next to Customer Service.'],
          ['Show your code', 'Bring the collection code and photo ID.'],
        ],
        qr: 'https://example.com/click-and-collect',
        qrLabel: 'Order online',
        footer: 'Collections until 30 minutes before close',
      },
    },
    {
      key: 'loyalty-signup',
      name: 'Loyalty Sign-Up',
      description: 'How to join the points scheme in four steps.',
      tags: ['loyalty', 'signup'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'violet',
        display: 'inter',
        title: 'Join The Club',
        steps: [
          ['Scan the code', 'Opens the sign-up form. Takes about a minute.'],
          ['Add your details', 'Name, email and postcode. No card needed.'],
          ['Start earning', 'One point for every pound you spend.'],
          ['Spend your points', '500 points is 5 pounds off any purchase.'],
        ],
        qr: 'https://example.com/loyalty',
        qrLabel: 'Join in a minute',
      },
    },
    {
      key: 'membership-tiers',
      name: 'Membership Tiers',
      description: 'Three loyalty tiers with benefits and annual price.',
      tags: ['loyalty', 'membership'],
      recipe: 'priceCards',
      orientation: 'landscape',
      spec: {
        palette: 'sand',
        display: 'oswald',
        title: 'Membership Tiers',
        subtitle: 'Every tier earns points on everything you buy',
        cards: [
          { name: 'Blue', price: 'Free', desc: 'One point per pound. A birthday treat every year.' },
          { name: 'Silver', price: '25 / yr', desc: 'Double points, free delivery, early sale access.', featured: true },
          { name: 'Gold', price: '60 / yr', desc: 'Triple points, free returns and personal styling.' },
        ],
        qr: 'https://example.com/membership',
        qrLabel: 'Compare tiers',
      },
    },
    {
      key: 'financing',
      name: 'Financing Options',
      description: 'Three ways to spread the cost on larger baskets.',
      tags: ['finance', 'payment'],
      recipe: 'priceCards',
      orientation: 'landscape',
      spec: {
        palette: 'teal',
        display: 'inter',
        title: 'Spread The Cost',
        subtitle: 'Available at every till and online',
        cards: [
          { name: 'Pay In 3', price: '0% APR', desc: 'Three monthly payments. No interest, no fees.' },
          { name: '12 Months', price: '0% APR', desc: 'Interest free on baskets over 500 pounds.', featured: true },
          { name: '24 Months', price: '9.9% APR', desc: 'Lower payments on furniture and appliances.' },
        ],
        qr: 'https://example.com/finance',
        qrLabel: 'Check eligibility',
        footer: 'Subject to status. Credit agreements apply.',
      },
    },
    {
      key: 'returns-policy',
      name: 'Returns Policy',
      description: 'Return window, online returns and the desk reference code.',
      tags: ['returns', 'policy', 'service'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'clinical',
        display: 'inter',
        title: 'Returns And Exchanges',
        fields: [
          { label: 'Return window', value: '90 days with a receipt' },
          { label: 'Online orders', value: 'Free returns to any store' },
          { label: 'Desk reference', value: 'RET-2026', mono: true },
        ],
        body: 'Unworn items with tags attached. Refunds go back to the original payment method.',
        qr: 'https://example.com/returns',
        qrLabel: 'Start a return',
      },
    },
    {
      key: 'gift-card',
      name: 'Gift Card Promo',
      description: 'Gift card offer with value range and validity.',
      tags: ['gifts', 'promo'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'rose',
        display: 'playfair',
        eyebrow: 'GIFT CARDS',
        title: 'Always The Right Size',
        titleSize: 0.11,
        body: 'Any amount from 10 to 500 pounds. Valid two years, in store and online.',
        cta: 'Ask at any till',
        flip: true,
        qr: 'https://example.com/gift-cards',
        qrLabel: 'Buy online',
      },
    },
    {
      key: 'why-shop-here',
      name: 'Why Shop With Us',
      description: 'Four proof-point tiles on service and reach.',
      tags: ['trust', 'stats'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        display: 'oswald',
        title: 'Why Shop With Us',
        subtitle: 'The bits that matter after you leave the till',
        tiles: [
          { label: 'Free returns', value: '90', sub: 'Days to change your mind' },
          { label: 'Click and collect', value: '2 hr', sub: 'Ready in store today' },
          { label: 'Stores', value: '128', sub: 'Across the country' },
          { label: 'Rating', value: '4.8', sub: 'From 22,000 reviews', accent: '#facc15' },
        ],
        footer: 'Ask a colleague in the green lanyard for help',
      },
    },
    {
      key: 'follow-us',
      name: 'Follow Us On Social',
      description: 'Portrait social follow poster with a scan code.',
      tags: ['social', 'poster'],
      recipe: 'announcement',
      orientation: 'portrait',
      spec: {
        palette: 'indigo',
        display: 'bebas',
        eyebrow: 'STAY IN THE LOOP',
        title: 'Follow The Store',
        titleSize: 0.11,
        body: 'New drops, restock alerts and member only sales. Scan to follow.',
        qr: 'https://example.com/social',
        qrLabel: 'Follow us',
        footer: 'northgate.store on every channel',
      },
    },
    {
      key: 'opening-soon',
      name: 'Opening Soon',
      description: 'Portrait teaser for a new store opening date.',
      tags: ['opening', 'poster'],
      recipe: 'heroOverlay',
      orientation: 'portrait',
      spec: {
        palette: 'espresso',
        display: 'bebas',
        eyebrow: 'OPENING SOON',
        title: 'Opening 12 March',
        titleSize: 0.1,
        body: 'A new home and lifestyle store on the corner of Bridge Street.',
        cta: 'Launch day offers all weekend',
        anchor: 'bottom',
        scrim: 70,
      },
    },
    {
      key: 'thank-you',
      name: 'Thank You Message',
      description: 'Warm closing message for the anniversary of the store.',
      tags: ['thanks', 'community'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'paper',
        display: 'playfair',
        eyebrow: 'FROM ALL OF US',
        title: 'Thank You',
        titleSize: 0.14,
        body: 'Twenty years on the high street, and it is all down to you.',
        footer: 'See you again soon',
      },
    },
  ],
}
