/* Transportation pack — stations, depots, bus interchanges and airport gates.
 *
 * The screens in this category do two jobs: they answer "when does mine leave
 * and from where", and they keep a moving crowd calm and informed. So the set
 * leans on scheduleRows and directory for the live boards, big single figures
 * for the next-departure countdowns, and loud announcement/stepList layouts for
 * disruption and platform safety.
 */

export default {
  category: 'transportation',
  name: 'Transportation',
  description: 'Departure boards, live times, fares and travel notices for rail, bus, transit and airports.',
  icon: '🚆',
  templates: [
    // ── live boards ─────────────────────────────────────────────────────────
    {
      key: 'departures-board',
      name: 'Departures Board',
      description: 'Eight upcoming departures with destination and platform.',
      tags: ['rail', 'departures', 'live'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        title: 'Departures',
        subtitle: 'MAIN CONCOURSE',
        colTime: 'DEPARTS',
        colName: 'DESTINATION',
        colMeta: 'PLATFORM',
        rows: [
          ['09:12', 'Manchester Piccadilly', 'Platform 4'],
          ['09:18', 'Edinburgh Waverley', 'Platform 7'],
          ['09:25', 'Bristol Temple Meads', 'Platform 2'],
          ['09:31', 'Cardiff Central', 'Platform 9'],
          ['09:40', 'Birmingham New Street', 'Platform 3'],
          ['09:47', 'Leeds', 'Platform 6'],
          ['09:55', 'Glasgow Central', 'Platform 1'],
          ['10:02', 'Norwich', 'Platform 11'],
        ],
        footer: 'Please stand behind the yellow line',
      },
    },
    {
      key: 'arrivals-board',
      name: 'Arrivals Board',
      description: 'Inbound services with origin and running status.',
      tags: ['rail', 'arrivals', 'live'],
      recipe: 'scheduleRows',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        title: 'Arrivals',
        subtitle: 'UPDATED LIVE',
        colTime: 'ARRIVES',
        colName: 'FROM',
        colMeta: 'STATUS',
        rows: [
          ['09:08', 'Liverpool Lime Street', 'On time'],
          ['09:16', 'York', 'On time'],
          ['09:22', 'Exeter St Davids', '5 min late'],
          ['09:34', 'Newcastle', 'On time'],
          ['09:41', 'Reading', 'On time'],
          ['09:53', 'Plymouth', '12 min late'],
          ['10:04', 'Sheffield', 'On time'],
        ],
        footer: 'Meet arriving passengers in the main hall, not on the platform',
      },
    },
    {
      key: 'route-timetable',
      name: 'Route Timetable',
      description: 'Portrait weekday timetable for a single bus route.',
      tags: ['bus', 'timetable'],
      recipe: 'scheduleRows',
      orientation: 'portrait',
      spec: {
        palette: 'charcoal',
        title: 'Route 14',
        subtitle: 'WEEKDAYS',
        colTime: 'DEPART',
        colName: 'VIA',
        colMeta: 'ARRIVE',
        rows: [
          ['06:15', 'City Hospital', '06:52'],
          ['06:45', 'City Hospital', '07:24'],
          ['07:10', 'Riverside Park', '07:51'],
          ['07:40', 'Riverside Park', '08:23'],
          ['08:05', 'City Hospital', '08:47'],
          ['08:35', 'Market Square', '09:14'],
          ['09:00', 'Riverside Park', '09:38'],
          ['09:30', 'City Hospital', '10:07'],
          ['10:00', 'Market Square', '10:36'],
        ],
        footer: 'Every 30 minutes until 23:00',
      },
    },
    {
      key: 'next-train',
      name: 'Next Train',
      description: 'Countdown to the next service on this platform.',
      tags: ['rail', 'live', 'countdown'],
      recipe: 'bigNumber',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        eyebrow: 'PLATFORM 2 SOUTHBOUND',
        value: '4 MIN',
        valueSize: 0.27,
        label: 'NEXT TRAIN',
        body: 'Eight carriages. Front four for Ashford, rear four for Harbour Point.',
        footer: 'Following service in 11 minutes',
      },
    },
    {
      key: 'next-bus',
      name: 'Next Bus',
      description: 'Portrait stop-side countdown for the next bus.',
      tags: ['bus', 'live', 'countdown'],
      recipe: 'bigNumber',
      orientation: 'portrait',
      spec: {
        palette: 'amber',
        eyebrow: 'STOP C ROUTE 14',
        value: '7 MIN',
        valueSize: 0.26,
        label: 'NEXT BUS DEPARTS',
        body: 'Low floor bus with wheelchair ramp. Contactless and day passes accepted.',
        footer: 'Live times at citytransit.example.com',
      },
    },
    {
      key: 'platform-directory',
      name: 'Platform Directory',
      description: 'Which service leaves from which platform.',
      tags: ['rail', 'wayfinding'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'steel',
        title: 'Platform Guide',
        entries: [
          ['Northern Line', 'PLAT 1'],
          ['Coast Express', 'PLAT 2'],
          ['Airport Shuttle', 'PLAT 3'],
          ['Valley Line', 'PLAT 4'],
          ['Metro West', 'PLAT 5'],
          ['Intercity 225', 'PLAT 6'],
          ['Harbour Local', 'PLAT 7'],
          ['Sleeper Service', 'PLAT 8'],
          ['Rail Replacement Bus', 'STAND A'],
          ['Ticket Office', 'CONCOURSE'],
          ['Assisted Travel Point', 'GATE LINE'],
          ['Left Luggage', 'LEVEL -1'],
        ],
        footer: 'Step-free access to every platform via the North Lift',
      },
    },
    {
      key: 'gate-directory',
      name: 'Airport Gate Directory',
      description: 'Departure gates for the next wave of flights.',
      tags: ['airport', 'gates', 'wayfinding'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'slate',
        title: 'Departure Gates',
        entries: [
          ['Amsterdam AS412', 'GATE 12'],
          ['Dublin EI338', 'GATE 14'],
          ['Madrid IB760', 'GATE 15'],
          ['Rome AZ221', 'GATE 18'],
          ['Paris AF1071', 'GATE 21'],
          ['Lisbon TP357', 'GATE 22'],
          ['Copenhagen SK502', 'GATE 24'],
          ['Zurich LX318', 'GATE 26'],
          ['Vienna OS456', 'GATE 27'],
          ['Oslo DY1101', 'GATE 30'],
          ['Berlin LH971', 'GATE 31'],
          ['Athens A3603', 'GATE 33'],
        ],
        footer: 'Gates close 20 minutes before departure',
      },
    },
    {
      key: 'station-facilities',
      name: 'Station Facilities',
      description: 'Where to find toilets, cafes, lifts and help points.',
      tags: ['station', 'facilities'],
      recipe: 'directory',
      orientation: 'landscape',
      spec: {
        palette: 'forest',
        title: 'Station Facilities',
        entries: [
          ['Ticket Office', 'CONCOURSE'],
          ['Toilets and Baby Change', 'LEVEL 1'],
          ['Accessible Toilet', 'LEVEL 1'],
          ['Left Luggage', 'LEVEL -1'],
          ['Cafe and Bakery', 'GATE LINE'],
          ['Cash Machine', 'MAIN HALL'],
          ['First Aid Point', 'PLAT 1'],
          ['Lost Property', 'NORTH END'],
          ['Waiting Room', 'PLAT 4'],
          ['Bicycle Racks', 'WEST EXIT'],
          ['Taxi Rank', 'EXIT B'],
          ['Bus Interchange', 'EXIT C'],
        ],
        footer: 'Help points on every platform connect you to staff 24 hours',
      },
    },

    // ── planning and information ────────────────────────────────────────────
    {
      key: 'route-map',
      name: 'Route Map Info',
      description: 'Line summary with a QR to the full network map.',
      tags: ['route', 'map', 'network'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'teal',
        eyebrow: 'COAST LINE',
        title: 'Every Stop, Every Hour',
        body: 'Twelve stations from Central to Harbour Point. Trains every 15 minutes until midnight.',
        cta: 'See the network map',
        qr: 'https://example.com/route-map',
        qrLabel: 'Route map',
      },
    },
    {
      key: 'journey-planner',
      name: 'Journey Planner QR',
      description: 'Scan to plan a door-to-door trip on your phone.',
      tags: ['planner', 'qr', 'app'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'clinical',
        eyebrow: 'PLAN YOUR TRIP',
        title: 'Journey Planner',
        titleSize: 0.11,
        display: 'inter',
        body: 'Live times, platforms and step-free routes across the whole network.',
        flip: true,
        cta: 'Scan to start',
        qr: 'https://example.com/journey-planner',
        qrLabel: 'Plan a journey',
      },
    },
    {
      key: 'welcome-to-the-city',
      name: 'Welcome to the City',
      description: 'Arrivals-hall welcome with onward travel in one line.',
      tags: ['welcome', 'arrivals', 'tourism'],
      recipe: 'heroOverlay',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        eyebrow: 'WELCOME TO',
        title: 'Harbour City',
        body: 'Trams to the old town leave every 10 minutes from Stand 3, straight outside.',
        cta: 'Enjoy your stay',
        anchor: 'bottom',
        scrim: 58,
      },
    },
    {
      key: 'destination-strip',
      name: 'Destinations Strip',
      description: 'Three photo frames with journey times to top stops.',
      tags: ['destinations', 'leisure'],
      recipe: 'photoStrip',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        title: 'Where the Coast Line Goes',
        subtitle: 'All within three hours of Central',
        frames: 3,
        captions: ['Harbour Point, 48 min', 'Valley Falls, 1 hr 25', 'Old Town Pier, 2 hr 10'],
        qr: 'https://example.com/days-out',
        qrLabel: 'Days out',
      },
    },

    // ── fares, parking and rules ────────────────────────────────────────────
    {
      key: 'ticket-prices',
      name: 'Ticket Prices',
      description: 'Single, return, day pass and concession fares.',
      tags: ['fares', 'tickets', 'prices'],
      recipe: 'menuBoard',
      orientation: 'landscape',
      spec: {
        palette: 'charcoal',
        title: 'Ticket Prices',
        subtitle: 'ZONES 1 TO 3',
        columns: 2,
        sections: [
          {
            name: 'SINGLE',
            items: [
              ['Zone 1', '$2.40'],
              ['Zones 1 to 2', '$3.60'],
              ['Zones 1 to 3', '$4.80'],
            ],
          },
          {
            name: 'RETURN',
            items: [
              ['Zone 1', '$4.20'],
              ['Zones 1 to 2', '$6.50'],
              ['Zones 1 to 3', '$8.90'],
            ],
          },
          {
            name: 'DAY PASS',
            items: [
              ['Adult', '$9.50'],
              ['Child 5 to 15', '$4.75'],
              ['Family of four', '$19.00'],
            ],
          },
          {
            name: 'CONCESSIONS',
            items: [
              ['Senior off-peak', '$2.10'],
              ['Student weekly', '$21.00'],
            ],
          },
        ],
        qr: 'https://example.com/fares',
        qrLabel: 'All fares',
        footer: 'Contactless and mobile tickets accepted at every gate',
      },
    },
    {
      key: 'travel-passes',
      name: 'Travel Passes',
      description: 'Day, weekly and monthly pass cards with prices.',
      tags: ['fares', 'passes', 'offers'],
      recipe: 'priceCards',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        title: 'Travel Passes',
        subtitle: 'Buy once, ride all week',
        cards: [
          { name: 'DAY', price: '$9.50', desc: 'Unlimited travel until 04:00 the next morning.' },
          { name: 'WEEKLY', price: '$34', desc: 'Seven days, all zones. Best value for commuters.', featured: true },
          { name: 'MONTHLY', price: '$118', desc: 'Thirty days, all zones, night buses included.' },
        ],
        qr: 'https://example.com/passes',
        qrLabel: 'Buy a pass',
      },
    },
    {
      key: 'parking-rates',
      name: 'Parking Rates',
      description: 'Station car park tariff by length of stay.',
      tags: ['parking', 'prices'],
      recipe: 'priceCards',
      orientation: 'landscape',
      spec: {
        palette: 'sand',
        title: 'Station Parking',
        subtitle: 'Pay at the machine or in the app',
        cards: [
          { name: '1 HOUR', price: '$2.50', desc: 'Ideal for drop-off and collection.' },
          { name: 'UP TO 4 HRS', price: '$6.00', desc: 'Covers most return trips into the city.' },
          { name: 'ALL DAY', price: '$11.00', desc: 'Free after 18:00 and all day Sunday.', featured: true },
          { name: 'WEEKLY', price: '$45.00', desc: 'Seven consecutive days, one vehicle.' },
        ],
        footer: 'Enter your registration at the machine before you travel',
      },
    },
    {
      key: 'luggage-rules',
      name: 'Luggage Rules',
      description: 'What travels free and what costs extra.',
      tags: ['luggage', 'rules', 'fees'],
      recipe: 'menuBoard',
      orientation: 'landscape',
      spec: {
        palette: 'steel',
        title: 'Luggage Allowance',
        subtitle: 'PER PASSENGER',
        columns: 2,
        sections: [
          {
            name: 'TRAVELS FREE',
            items: [
              ['Cabin bag', 'Free', 'Max 40 x 30 x 20 cm, under the seat'],
              ['Hold suitcase', 'Free', 'Up to 23 kg, one per ticket'],
              ['Pushchair or wheelchair', 'Free', 'Folded and stowed in the rack'],
            ],
          },
          {
            name: 'EXTRA CHARGE',
            items: [
              ['Second suitcase', '$18'],
              ['Overweight 23 to 32 kg', '$25'],
              ['Boxed bicycle', '$15'],
              ['Surfboard or skis', '$30'],
            ],
          },
        ],
        footer: 'Never leave bags unattended. Unattended items will be removed.',
      },
    },
    {
      key: 'fuel-and-charging',
      name: 'Fuel and Charging Prices',
      description: 'Forecourt fuel and EV tariffs on one board.',
      tags: ['fuel', 'ev', 'prices'],
      recipe: 'menuBoard',
      orientation: 'landscape',
      spec: {
        palette: 'espresso',
        title: 'Fuel and Charging',
        subtitle: 'TODAY',
        columns: 2,
        sections: [
          {
            name: 'FORECOURT PER LITRE',
            items: [
              ['Unleaded 95', '$1.62'],
              ['Unleaded 98', '$1.79'],
              ['Diesel', '$1.71'],
              ['AdBlue', '$1.05'],
            ],
          },
          {
            name: 'EV PER KWH',
            items: [
              ['Rapid 150 kW', '$0.54'],
              ['Fast 22 kW', '$0.39'],
              ['Overnight after 22:00', '$0.28'],
            ],
          },
        ],
        footer: 'Fleet cards accepted at pumps 1 to 6',
      },
    },
    {
      key: 'ev-charging-bays',
      name: 'EV Charging Bays',
      description: 'Bay numbers, price and maximum stay for chargers.',
      tags: ['ev', 'charging', 'parking'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'violet',
        title: 'EV Charging Bays',
        fields: [
          { label: 'RAPID CHARGERS', value: 'Bays 21 to 26, 150 kW' },
          { label: 'PRICE', value: '$0.54 per kWh' },
          { label: 'MAXIMUM STAY', value: '45 minutes' },
        ],
        qr: 'https://example.com/ev-charging',
        qrLabel: 'Start a charge',
        body: 'An overstay fee applies once charging completes. Please move promptly.',
      },
    },

    // ── disruption, safety and service ──────────────────────────────────────
    {
      key: 'service-disruption',
      name: 'Service Disruption Alert',
      description: 'Loud red notice for a suspended line.',
      tags: ['alert', 'disruption'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'crimson',
        eyebrow: 'SERVICE ALERT',
        title: 'Coast Line Suspended',
        titleSize: 0.12,
        body: 'Signal fault at Harbour Point. Replacement buses leave Stand A every 20 minutes.',
        footer: 'Tickets valid on Metro West until further notice',
      },
    },
    {
      key: 'engineering-works',
      name: 'Planned Engineering Works',
      description: 'Advance warning of a weekend line closure.',
      tags: ['alert', 'planned', 'closure'],
      recipe: 'announcement',
      orientation: 'landscape',
      spec: {
        palette: 'amber',
        eyebrow: 'PLANNED WORKS',
        title: 'No Trains This Sunday',
        titleSize: 0.115,
        body: 'Track renewal between Central and Valley Junction. Buses replace trains 05:00 to 23:00.',
        qr: 'https://example.com/engineering-works',
        qrLabel: 'Check your route',
      },
    },
    {
      key: 'platform-safety',
      name: 'Safety on the Platform',
      description: 'Five platform safety rules as numbered steps.',
      tags: ['safety', 'platform', 'steps'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'steel',
        title: 'Safety on the Platform',
        steps: [
          ['Stand behind the yellow line', 'Fast trains pass through this station without stopping.'],
          ['Mind the gap', 'Watch your step between the train and the platform edge.'],
          ['Hold the handrail', 'Stairs and escalators get slippery in wet weather.'],
          ['Brake pushchairs and cases', 'Apply the brake whenever you stop on the platform.'],
          ['Report anything unattended', 'Tell a staff member or use the nearest help point.'],
        ],
        footer: 'In an emergency press the red button on any help point',
      },
    },
    {
      key: 'travel-tips',
      name: 'Travel Tips',
      description: 'Five ways to make the journey cheaper and calmer.',
      tags: ['tips', 'steps', 'advice'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'forest',
        title: 'Travel Smarter',
        steps: [
          ['Check before you leave', 'Live times and platforms refresh every 30 seconds in the app.'],
          ['Travel off-peak', 'Fares drop by a third after 09:30 and all weekend.'],
          ['Use the quiet coaches', 'Coaches A and B are quiet zones on every intercity service.'],
          ['Board down the platform', 'The rear carriages are almost always the emptiest.'],
          ['Let people off first', 'Then move right down inside the carriage.'],
        ],
        footer: 'Ask any member of staff in a red vest for help',
      },
    },
    {
      key: 'tap-and-go',
      name: 'How to Tap and Go',
      description: 'Four steps to paying by card or phone.',
      tags: ['tickets', 'howto', 'steps'],
      recipe: 'stepList',
      orientation: 'landscape',
      spec: {
        palette: 'teal',
        title: 'How to Tap and Go',
        steps: [
          ['Pick one card', 'Use the same card or phone for every journey that day.'],
          ['Touch the yellow reader', 'Wait for the green light before you walk through.'],
          ['Touch out at the end', 'A missing tap out charges the maximum fare.'],
          ['Let the cap do the maths', 'You never pay more than the day pass price.'],
        ],
        footer: 'No ticket needed. Fares are capped automatically.',
      },
    },
    {
      key: 'lost-property',
      name: 'Lost Property Notice',
      description: 'Portrait notice for the lost property office.',
      tags: ['lost', 'notice', 'help'],
      recipe: 'announcement',
      orientation: 'portrait',
      spec: {
        palette: 'violet',
        eyebrow: 'LOST SOMETHING',
        title: 'Lost Property Office',
        titleSize: 0.1,
        body: 'North end of the concourse, open 07:00 to 20:00 daily. Bring photo identification.',
        qr: 'https://example.com/lost-property',
        qrLabel: 'Report an item',
        footer: 'Items are held for 30 days',
      },
    },

    // ── onward travel and onboard ───────────────────────────────────────────
    {
      key: 'taxi-and-rideshare',
      name: 'Taxi and Rideshare Pickup',
      description: 'Where licensed taxis and app pickups wait.',
      tags: ['taxi', 'rideshare', 'onward'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'charcoal',
        title: 'Taxi and Rideshare',
        fields: [
          { label: 'LICENSED TAXI RANK', value: 'Exit B, ground level' },
          { label: 'RIDESHARE PICKUP', value: 'Car Park 2, Bay 14' },
          { label: 'ACCESSIBLE VEHICLES', value: 'Call 555 0142' },
        ],
        qr: 'https://example.com/pickup-map',
        qrLabel: 'Pickup map',
        body: 'Only use licensed vehicles. Never accept a ride offered inside the terminal.',
      },
    },
    {
      key: 'wifi-on-board',
      name: 'Wi-Fi On Board',
      description: 'Network name, password and session limit.',
      tags: ['wifi', 'onboard', 'guest'],
      recipe: 'infoCard',
      orientation: 'landscape',
      spec: {
        palette: 'indigo',
        title: 'Free Wi-Fi On Board',
        fields: [
          { label: 'NETWORK', value: 'CoastLine-Free', mono: true },
          { label: 'PASSWORD', value: 'ridefree2026', mono: true },
          { label: 'SESSION LIMIT', value: '4 hours per device' },
        ],
        qr: 'https://example.com/wifi',
        qrLabel: 'Connect',
        body: 'Signal drops in the tunnels between Central and Harbour Point.',
      },
    },

    // ── operator and people ─────────────────────────────────────────────────
    {
      key: 'fleet-stats',
      name: 'Fleet Stats',
      description: 'Six operating numbers for the last thirty days.',
      tags: ['stats', 'fleet', 'performance'],
      recipe: 'statTiles',
      orientation: 'landscape',
      spec: {
        palette: 'ocean',
        title: 'Fleet Performance',
        subtitle: 'LAST 30 DAYS',
        tiles: [
          { label: 'ON TIME', value: '94.6%', sub: 'Within three minutes' },
          { label: 'SERVICES RUN', value: '12,480', sub: 'Across nine routes' },
          { label: 'PASSENGERS', value: '1.9M', sub: 'Journeys completed' },
          { label: 'ELECTRIC BUSES', value: '62', sub: 'Of 110 vehicles' },
          { label: 'DAYS INCIDENT FREE', value: '214', sub: 'Depot wide', accent: '#22c55e' },
          { label: 'AVERAGE WAIT', value: '6 min', sub: 'Peak city routes' },
        ],
        footer: 'Figures published monthly at citytransit.example.com/performance',
      },
    },
    {
      key: 'driver-of-the-month',
      name: 'Driver of the Month',
      description: 'Photo and citation for a recognised driver.',
      tags: ['staff', 'recognition'],
      recipe: 'heroSplit',
      orientation: 'landscape',
      spec: {
        palette: 'amber',
        eyebrow: 'DRIVER OF THE MONTH',
        title: 'Priya Raman',
        body: 'Route 14. Twelve years accident free and forty-one passenger compliments this quarter.',
        flip: true,
        cta: 'Congratulations, Priya',
      },
    },
    {
      key: 'passenger-charter',
      name: 'Passenger Charter',
      description: 'Pull quote setting out the delay refund promise.',
      tags: ['charter', 'quote', 'trust'],
      recipe: 'quoteCard',
      orientation: 'landscape',
      spec: {
        palette: 'paper',
        quote: 'If your train is 15 minutes late, we refund the fare. No forms, no fuss.',
        quoteSize: 0.055,
        author: 'THE PASSENGER CHARTER',
        footer: 'Claim in the app within 28 days of travel',
      },
    },
    {
      key: 'family-offer',
      name: 'Kids Ride Free Promo',
      description: 'Portrait weekend promo with code and QR.',
      tags: ['promo', 'offer', 'family'],
      recipe: 'promoBurst',
      orientation: 'portrait',
      spec: {
        palette: 'rose',
        eyebrow: 'WEEKEND OFFER',
        title: 'Kids Ride Free',
        titleSize: 0.13,
        body: 'Up to four children travel free with every adult day pass.',
        code: 'FAMILY26',
        qr: 'https://example.com/family-offer',
        qrLabel: 'Get the offer',
        footer: 'Saturdays and Sundays on all buses and trams',
      },
    },
  ],
}
